### PR TITLE
Issue #2396: Resolve Infantry part and other part type bugs

### LINKED ISSUE #2396: Unable to load saved 47.16 campaign
After saving a campaign in 47.16, I cannot load it, or most of the auto-saves.  The only thing I can point to, is

- a change to a conventional infantry platoon, which seems to show up in the log.
- an exception being thrown about battle armor

[Brilliant Light III-Gamma30741228.cpnx.gz](https://github.com/MegaMek/mekhq/files/5861613/Brilliant.Light.III-Gamma30741228.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5861614/megameklog.txt)
[BIIIG Customs.zip](https://github.com/MegaMek/mekhq/files/5861615/BIIIG.Customs.zip)
[BIIIG-BA.zip](https://github.com/MegaMek/mekhq/files/5861618/BIIIG-BA.zip)

### PR DESCRIPTION
**Pull request by sixlettervariables**
When we initialize a unit, there are certain assumptions about where a part came from. If a refit went "bad" and picked the wrong type of part, you can end up in a situation where the unit cannot be initialized. Two approaches are taken here to resolve this issue:
1. If the entity type for a BA part isn't BattleArmor, remove the part from the unit.
2. For all of the sub-classes and extendable parts, make `isSamePartType` use strict class equality rather than `instanceof`.

The first approach directly fixes #2396.

The second approach hopes to make this a non-issue going forward. We shot ourselves in the foot a bit where we have base classes that are not abstract. Ideally, EquipmentPart would be abstract (as would Armor and AmmoBin), and the various type or entity specific classes would inherit from them. At that point `instanceof` would be a valid check.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java [hunk 1]
```diff
@@ -121,7 +122,8 @@ public boolean isAcceptableReplacement(Part part, boolean refit) {
         // than an LargeCraftAmmoBin. Subclasses should use a similar check, which
         // breaks Composability to a degree but in this case we've used
         // subclasses where they're not truly composable.
-        if ((part instanceof LargeCraftAmmoBin) && (part.getClass() == LargeCraftAmmoBin.class)) {
+        if ((part instanceof LargeCraftAmmoBin)
+                && Objects.equals(part.getClass(), LargeCraftAmmoBin.class)) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java:126]: Why the instanceof usage here? Wouldn't that be covered in the Objects.equals?

File: MekHQ/src/mekhq/campaign/unit/Unit.java [hunk 2]
```diff
@@ -2325,19 +2327,27 @@ public void initializeParts(boolean addParts) {
...
-                    parts = new Part[((BattleArmor)entity).getSquadSize()];
+                if (!(entity instanceof BattleArmor)) {
+                    partsToRemove.add(part);
+                } else {
+                    Part[] parts = baEquipParts.get(((MissingBattleArmorEquipmentPart)part).getEquipmentNum());
+                    if (null == parts) {
+                        parts = new Part[((BattleArmor)entity).getSquadSize()];
+                    }
+                    parts[((MissingBattleArmorEquipmentPart)part).getTrooper()-BattleArmor.LOC_TROOPER_1] = part;
+                    baEquipParts.put(((MissingBattleArmorEquipmentPart)part).getEquipmentNum(), parts);
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/unit/Unit.java:2349]:
```suggestion
                    Part[] parts = baEquipParts.get(((MissingBattleArmorEquipmentPart) part).getEquipmentNum());
                    if (null == parts) {
                        parts = new Part[((BattleArmor) entity).getSquadSize()];
                    }
                    parts[((MissingBattleArmorEquipmentPart) part).getTrooper() - BattleArmor.LOC_TROOPER_1] = part;
                    baEquipParts.put(((MissingBattleArmorEquipmentPart) part).getEquipmentNum(), parts);
```

File: MekHQ/src/mekhq/campaign/unit/Unit.java [hunk 3]
```diff
@@ -2325,19 +2327,27 @@ public void initializeParts(boolean addParts) {
...
-                    parts = new Part[((BattleArmor)entity).getSquadSize()];
+                if (!(entity instanceof BattleArmor)) {
+                    partsToRemove.add(part);
+                } else {
+                    Part[] parts = baEquipParts.get(((BattleArmorEquipmentPart)part).getEquipmentNum());
+                    if (null == parts) {
+                        parts = new Part[((BattleArmor)entity).getSquadSize()];
+                    }
+                    parts[((BattleArmorEquipmentPart)part).getTrooper()-BattleArmor.LOC_TROOPER_1] = part;
+                    baEquipParts.put(((BattleArmorEquipmentPart)part).getEquipmentNum(), parts);
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/unit/Unit.java:2338]:
```suggestion
                    Part[] parts = baEquipParts.get(((BattleArmorEquipmentPart) part).getEquipmentNum());
                    if (null == parts) {
                        parts = new Part[((BattleArmor) entity).getSquadSize()];
                    }
                    parts[((BattleArmorEquipmentPart) part).getTrooper() - BattleArmor.LOC_TROOPER_1] = part;
                    baEquipParts.put(((BattleArmorEquipmentPart) part).getEquipmentNum(), parts);
```

**Review by Windchild292 — COMMENTED** [review]
One query first before I approve.

File: MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java (hunk 1 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java:126]: I originally only had the get-class check on the base classes and just had instanceof in the subclasses, however I must not have doubled back and removed that here.

**Review by Windchild292 — APPROVED** [review]
