### PR TITLE
Fix #7897: Fixed Legendary MekWarriors Not Counting Towards CamOps Reputation

### LINKED ISSUE #7897: [Issue] 50.07 Nightly 11-1  Pilots with 0/0 Don't seem to contribute properly to Unit Experience Rating.
### Brief Description *

I made a test unit and cheated all combat personnel to 0/0 skill.  The unit experience shows that my unit has an experience level of "none" when it should be "legendary."

### 3. Steps to Reproduce

Create a Unit.
Add several mekwarriors and GM edit their skills to some level other than 0/0.
Advance to monday and verify experience level is set.
Cheat their skills to 0/0
Advance to another monday and the experience level will set to "none"

### Attach Files

_No response_

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

50.07 Nightly 11-1

### Operating System *

Windows 10

### Java Version *

17.0.14

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #7897

This came about from a very early misunderstanding of the rules when translating mhq to CamOps. The original interpretation was that we should be comparing total skill level. However, skill levels are an ATOW thing, not TW. CamOps expected us to be comparing skill _target numbers_.

Under the original interpretation a total skill level of `0` would mean the character had no skill whatsoever. As opposed to `0+` meaning the character is the most skilled thing ever.

As we were still checking if the experience score was `>0` any legendary characters were being incorrectly treated as if they were completely unskilled.

This only affected MekWarriors. Proof that 'Meks really aren't the 'kings of the battlefield.'

As a secondary fix I also made sure to include a special handler for Combat Technicians, as they were being incorrectly included in the calculations. It's possible they were being excluded elsewhere - and I think they were - but a little insurance never hurt and adding a single conditional clause isn't going to hurt anyone.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java [hunk 1]
```diff
@@ -212,7 +213,7 @@ private static int calculateAverageExperienceRating(Campaign campaign, boolean l
                 if (unit.isGunner(person) || unit.isDriver(person)) {
                     totalExperience += calculateRegularExperience(person, entity, unit);
 
-                    if (totalExperience > 0) {
+                    if (totalExperience >= 0) {
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: Good catch, Copilot

File: MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java [hunk 2]
```diff
@@ -153,9 +154,9 @@ private static int calculateAverageExperienceRating(Campaign campaign, boolean l
                 continue;
             }
 
-            // if both primary and secondary roles are support roles, skip this person
-            // as they are also not considered combat personnel
-            if (person.getPrimaryRole().isSupport() && person.getSecondaryRole().isSupport()) {
+            // if both primary and secondary roles are support roles, skip this person as they are also not
+            // considered combat personnel. The 'isTech' check is to catch Combat Technicians
+            if (person.isTechExpanded() || person.isSupport()) {
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: Will this exclude Mekwarriors that have a secondary profession that's a tech? It looks like `isTechExpanded()` & the methods it calls check if the primary or secondary role a tech.

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: That is a _very_ good question, let's find out

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: Fixed

Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: What about `isSupport()` - that also looks to return true if either role is support.

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: isSupport returns false if either profession is combat

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: Though there is a bug here. Fixing

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java]: I came up with a better solution: #7923

**Review by psikomonkie — APPROVED** [review]
Nice!
