### PR TITLE
Fixed Role Eligibility Checks and Ensured Proper Role Assignment

### LINKED ISSUE #5580: 50.02 NullPointerException on Unit Rating report
### Prerequisites and Pre-Issue Checklist

- [ ] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Upon starting the unit rating report a NullPointerException is thrown. The Campaign Ops Method is set for Unit Reputation.

12:53:10,766 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:296) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at mekhq.campaign.rating.CamOpsReputation.ReputationController.getReportText(ReputationController.java:320)
	at mekhq.gui.dialog.reportDialogs.ReputationReportDialog.createTxtReport(ReputationReportDialog.java:49)
	at mekhq.gui.dialog.reportDialogs.AbstractReportDialog.createCenterPane(AbstractReportDialog.java:43)
	at megamek.client.ui.baseComponents.AbstractDialog.initialize(AbstractDialog.java:155)
	at mekhq.gui.dialog.reportDialogs.ReputationReportDialog.<init>(ReputationReportDialog.java:34)
	at mekhq.gui.CampaignGUI.lambda$initMenu$45(CampaignGUI.java:886)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Steps to Reproduce

MekHQ main UI: Reports ...  Unit Rating

### Operating System *

Windows 11

### Java Version *

21

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.02

### Attach Files

Version information

    MekHQ v0.50.02
    Build Date: 2024-12-30T14:34:16.202038100
    Today: 2025-01-01
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.2
    Platform: Windows 11 10.0 (amd64)
    System Locale: de_DE
    Total memory available to MekHQ: 4 GB
    MM Code Revision: 2bc80c102a745fedbb40039b75202ecdfcf4d8d2
    MML Code Revision: 218b264a92737d8dfc7b65952e4eac8e5a085062
    MHQ Code Revision: 28c61bbccb0f3c650181c33b74ad2bb654912eec

[mekhq.log](https://github.com/user-attachments/files/18285367/mekhq.log)

Further game files / custom files can be provided on request (they are quite large).

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### LINKED ISSUE #5740: [Issue] Selecting multiple personnel who have completed their last day of training but not formally finished the education track and returned to the unit allows assigning unavailable jobs to selected personnel
### Brief Description *

image

Ataun here just failed out of an Admin course. His fellow freebirth soldiers are training to be medics. It's graduation day for them, and dropout day for him. However, if I select the entire group of trainees, including Ataun, I am able to assign Medic to him (and other non-medics). I can also assign vehicle crewmember, which I think comes along with medic now.

image

The end result is repeatable and allows this;

image

### 3. Steps to Reproduce

1. Have troops graduated / failed / needing more classes and in limbo between education and returning to unit
2. Select all graduating / failed / needing more classes individuals stuck in said limbo, right click, set role... 
3. It shows medic, vehicle crewmember, and soldier (the latter of which they already had, but the prior two some of them didn't have), and allows whatever is selected to be set for primary or secondary.

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18370005/logs.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.03 SNAPSHOT from 01/06 Nightly

### Operating System *

Windows 10

### Java Version *

17

### Final Verification

- [X] I confirm this is a single, unique issue that hasn't been reported before
- [X] I have filled and provided all necessary information above
- [X] I have included any and all logs, custom units, and CPNX (save) files
- [X] I have asked on MegaMek Discord about this issue
- [X] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Removed redundant `Person` parameter in `canPerformRole`.
- Removed 'must be Green' expertise requirement from Tech roles -- I could have sworn I removed this before, but apparently not. So, removing it here. This ensures these roles are treated like all others, none of which require minimum expertise.
- Fixed a very long standing bug where, when assigning personnel to roles, we only checked the eligibility of the first selected character and then assumed all other characters' eligibility matched theirs. Now we correctly check the eligibility of all selected characters.
- Added sanitizers to ensure all personnel are eligible for their assigned roles, on load, and unassigning them if they're not.

Fix #5740, Fix #5580

### CODE REVIEW

File: MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java [hunk 1]
```diff
@@ -1489,26 +1489,48 @@ protected Optional<JPopupMenu> createPopupMenu() {
...
                 menu.add(cbMenuItem);
             }
         }
         JMenuHelpers.addMenuIfNonEmpty(popup, menu);
 
         menu = new JMenu(resources.getString("changeSecondaryRole.text"));
         for (final PersonnelRole role : roles) {
-            if (person.canPerformRole(gui.getCampaign().getLocalDate(), person, role, false)) {
-                cbMenuItem = new JCheckBoxMenuItem(role.getName(person.isClanPersonnel()));
+            boolean allCanPerform = true;
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java:1518]: It looks like this & the canAllPerform are doing the same boolean check. Do you think would be checked again/should we extract it into a method?

**Review by psikomonkie — APPROVED** [review]

**Review by HammerGS — APPROVED** [review]
Reviewed with Co-Pilot and IDEA AI
