### PR TITLE
Issue #2217 #2219: Cannot save Campaign with Refits and cannot start new Refits

### LINKED ISSUE #2217: [47.13] Save failed, NPE in Log
### Environment
MekHQ 47.13
Windows
Java OpenJDK 1.8.0_265

After loading a campaign from a previous version (30310211b), advanced a day, played one scenario, and was unable to save (30310212), with error https://imgur.com/a/nBlS0Gs. Advanced an additional day (30310213), attempted to save again, received the same error. Save files were generated and have been attached.
Recreation; Loading 30310211B, advancing one day, and attempting to save should generate the above error again.

### Files
[The White Wolf Squadron30310213.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513112/The.White.Wolf.Squadron30310213.cpnx.gz)
[The White Wolf Squadron30310212.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513113/The.White.Wolf.Squadron30310212.cpnx.gz)
[The White Wolf Squadron30310211b.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513114/The.White.Wolf.Squadron30310211b.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/5513118/Customs.zip)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5513122/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5513123/mekhqlog.txt)

### LINKED ISSUE #2219: 47.13 Cannot Refit
47.13
Cannot refit units, window fails to appear for refit kit selection.

[Cavaliere Ghiottone30550103.cpnx.gz](https://github.com/MegaMek/mekhq/files/5514405/Cavaliere.Ghiottone30550103.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5514406/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5514407/mekhqlog.txt)

### PR DESCRIPTION
**Pull request by sixlettervariables**
Refactoring to use `getCampaign` introduced an error where two places should have been using `oldUnit.getCampaign`. This fixes #2217. This fixes #2219.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/Refit.java [hunk 1]
```diff
@@ -2101,12 +2101,12 @@ private static void processArmorSupplies(Refit retVal, Node wn, Version version)
     }
 
     public void reCalc() {
-        setCampaign(getCampaign());
+        setCampaign(oldUnit.getCampaign());
         for (Part p : shoppingList) {
-            p.setCampaign(getCampaign());
+            p.setCampaign(oldUnit.getCampaign());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/Refit.java:2106]: getCampaign is correct here as we just set campaign to be this value.

File: MekHQ/src/mekhq/campaign/parts/Refit.java [hunk 2]
```diff
@@ -2101,12 +2101,12 @@ private static void processArmorSupplies(Refit retVal, Node wn, Version version)
...
         }
         if (null != newArmorSupplies) {
-            newArmorSupplies.setCampaign(getCampaign());
+            newArmorSupplies.setCampaign(oldUnit.getCampaign());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/Refit.java:2109]: Same here

File: MekHQ/src/mekhq/campaign/parts/Refit.java [hunk 3]
```diff
@@ -2101,12 +2101,12 @@ private static void processArmorSupplies(Refit retVal, Node wn, Version version)
     }
 
     public void reCalc() {
-        setCampaign(getCampaign());
+        setCampaign(oldUnit.getCampaign());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/Refit.java:2104]: With the addition of setCampaign in fixReferences this is not necessary at this time, although I don't know if it may come up in future.

**Review by Windchild292 — APPROVED** [review]
Approved, but with a few comments
