### PR TITLE
Fix #7915: Fixed Doctor & MASH Capacity Warnings Not Displaying; Updated Glossary Entry

### LINKED ISSUE #7915: [Issue] Unable to assign patient to doctor in Infirmary tab
### Brief Description *

Upon using the unit generator, one MechWarrior in my unit gave birth and was assigned the 'postpartum recovery' injury. However, I am unable to assign the MechWarrior to my doctor and pressing "Optimize Assignment" does not do anything.

I used GM mode to remove the 'postpartum recovery' injury and advanced a few days, I then manually added a broken leg injury to the same MechWarrior and advanced the day again. Same issue on the infirmary tab.

I have the Alternate Advanced Medical rule enabled. 

### 3. Steps to Reproduce

_No response_

### Attach Files

[Autosave-1-MVP's Gunslingers-30200102.cpnx.gz](https://github.com/user-attachments/files/23290600/Autosave-1-MVP.s.Gunslingers-30200102.cpnx.gz)

[unified_log.log](https://github.com/user-attachments/files/23290603/unified_log.log)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

MekHQ-0.50.10-nightly-2025-11-02

### Operating System *

Windows 11

### Java Version *

Adoptium 17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Close #7915

In the campaign summary there is a field for Doctor & MASH Theater Capacity. This was incorrectly fetching the number of concurrent patients and _not_ the number of injured personnel. This meant that it would never report as being over capacity, even if it was.

Furthermore, I went ahead and rebranded 'Hospital Beds' to 'Doctor Capacity'. This is less thematic, but more true to what it is and should help resolve any confusion.

Finally, I shifted the summary text into a RESOURCE_BUNDLE so that it's easier to manage in future.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/Campaign.java [hunk 1]
```diff
@@ -3010,6 +3010,13 @@ public List<Person> getPatientsAssignedToDoctors() {
                      .toList();
     }
 
+    public List<Person> getInjuredPersonnel() {
+        return getPatients()
+                     .stream()
+                     .filter(patient -> !patient.getInjuries().isEmpty() || patient.getHits() > 0)
+                     .toList();
+    }
+
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/Campaign.java]: How does this differ from `getPatients`? It looks like it should get the same bunch of patients in either case.

**Review by psikomonkie — APPROVED** [review]
Nice!! One Q about the new method in `Campaign`, but that's just preventing duplicate code and not a deal breaker (I think).

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/Campaign.java]: getPatients returns personnel who have a doctor assigned. This returns anyone who is injured - whether they have a doctor assigned or no.

The difference is important because in the summary we don't care about how many patients are assigned to doctors we care about how many patients _could_ be assigned to doctors. That was the root cause of the bug that stopped us from warning the player when they didn't have enough capacity.

Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Not `getPatientsAssignedToDoctors()` but `getPatients()`

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Oh! I completely forgot we had that method, switching.

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Fixed

**Review by psikomonkie — APPROVED** [review]
Nice!!

File: MekHQ/resources/mekhq/resources/GlossaryEntry.properties [hunk 2]
```diff
@@ -508,18 +508,18 @@ GROUP_BY_UNIT.definition=Group by Unit is an option in the Personnel Tab that ca
...
  <p>In Campaign Options, There's an option for Doctors to use the <i>Administration</i> skill. If enabled, the number\
- \ of beds each Doctor can support is adjusted depending on their <i>Administration</i> skill. No <i>Administration</i>\
- \ skill means the Doctor can support only 10 beds. With Ultra-Green allowing them to support 15 beds, 20 for Green, 25\
- \ for Regular, 30 for Veteran, and 35 for Elite+.</p>\
+ \ of patients each Doctor can support is adjusted depending on their <i>Administration</i> skill. No \
+  <i>Administration</i> skill means the Doctor can support only 10 patients. With Ultra-Green allowing them to support\
+  \ 15 patients, 20 for Green, 25 for Regular, 30 for Veteran, and 35 for Elite+.</p>\
   <p>Also, in Campaign Options, there is an option to enable <i>MASH Theatre Tracking</i>. If enabled, your maximum \
-  number of concurrent patients is limited by the number of MASH Theatre-equipped units you have in your TO&E. To \
+  number of concurrent patients is limited by the number of MASH Theater-equipped units you have in your TO&E. To \
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/resources/mekhq/resources/GlossaryEntry.properties:519]: Non-issue
