### PR TITLE
Fix fighter avionics repair time

### LINKED ISSUE #2854: Aerospace components repair time
### Environment
0.49.3
Platform Windows 10 10.0 (amd64)
Java version 11.0.12
	

### Description
Aerospace asset repair times high or low.
FCS has 0 minute repair time
Other components in the 1000s of minutes

image

[My Campaign30500114.cpnx.gz](https://github.com/MegaMek/mekhq/files/7084727/My.Campaign30500114.cpnx.gz)

### PR DESCRIPTION
**Pull request by Saklad5**
CamOps says that avionics repair takes 80 hours for Large Craft and 8 hours for other aerospace units: MekHQ was previously using 80 hours for everything.

Fixes #2854

### CODE REVIEW

**Review by HammerGS — APPROVED** [review]

File: MekHQ/src/mekhq/campaign/parts/MissingAvionics.java [hunk 1]
```diff
@@ -60,8 +60,12 @@ public int getBaseTime() {
                 time = 600;
             }
             return time;
+	// CamOps, 3rd printing, page 207: 80 hours for Large Craft, 8 hours otherwise
```
Comment (NickAragua) [inline MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:63]: I feel like we should just remove that option and go with the latest printing at this point.

**Review by NickAragua — CHANGES_REQUESTED** [review]

File: MekHQ/src/mekhq/campaign/parts/MissingAvionics.java (hunk 1 above)
Comment (NickAragua) [reply MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:63]: Yeah, that's basically what I'm getting at.

Comment (Saklad5) [reply MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:63]: Could we remove the option in a different pull request? I'm not familiar with everything that has to be changed, and it could break saved presets in a way this fix won't.

Comment (NickAragua) [reply MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:63]: Sure, why not.

**Review by NickAragua — APPROVED** [review]
