### PR TITLE
Issue 6651: Removed Partial Maintenance and fixed Shorthanded Penalty

### LINKED ISSUE #6651: [Issue] Partial maintenance and shorthanded penalties on every maintenance check
### Brief Description *

Partial maintenance and shorthanded penalties on every maintenance check.

### 3. Steps to Reproduce

Started fresh campaign on default "full experience" settings

### Attach Files

[maint.cpnx.gz](https://github.com/user-attachments/files/19724644/maint.cpnx.gz)

[logs.zip](https://github.com/user-attachments/files/19724647/logs.zip)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

v0.50.05-SNAPSHOT

### Operating System *

Windows 10

### Java Version *

17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6651 

Partial maintenance is no longer a thing. Shorthanded only cares about astech minutes on the day-of.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/Campaign.java [hunk 1]
```diff
@@ -8935,7 +8921,7 @@ public void doMaintenance(Unit unit) {
                                                                       " performing maintenance</strong><br><br>");
             for (Part p : unit.getParts()) {
                 try {
-                    String partReport = doMaintenanceOnUnitPart(unit, p, partsToDamage, paidMaintenance);
+                    String partReport = doMaintenanceOnUnitPart(unit, p, partsToDamage, paidMaintenance, asTechsUsed);
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/Campaign.java:8924]: Can we change p into a more descriptive variable name?

File: MekHQ/src/mekhq/campaign/Campaign.java [hunk 2]
```diff
@@ -9030,13 +9016,14 @@ public void doMaintenance(Unit unit) {
         }
     }
 
-    private String doMaintenanceOnUnitPart(Unit u, Part p, Map<Part, Integer> partsToDamage, boolean paidMaintenance) {
+    private String doMaintenanceOnUnitPart(Unit u, Part p, Map<Part, Integer> partsToDamage, boolean paidMaintenance,
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/Campaign.java:9019]: Descriptive variable names please. I absolutely know this isn’t your code, but we should be trying to update variable names from single letter and abbreviations whenever reasonable

**Review by IllianiBird — APPROVED** [review]
Two nitpicks, but nothing to stop this getting merged. Thanks for jumping on it so quickly

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 2 above)
Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Done!

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Yep, done!

**Comment by psikomonkie** [comment]
> Two nitpicks, but nothing to stop this getting merged. Thanks for jumping on it so quickly

Renamed the variables as requested, thanks Illiani!
