### PR TITLE
Fixed Multiple Gray Monday Bugs

### LINKED ISSUE #6017: [0.50.04-SNAPSHOT] Gray Monday Tests and Issues
### Brief Description *

Testing the new Gray Monday mechanic as requested. Issues found:
- Typo on one of the dialog panes
- Contract monthly payment went negative instead of zeroing out (and actually deducts money each month)
- I was in transit to contract when Gray Monday hit, and could not reach my destination due to my account balance becoming 1% suddenly
- I WAS able to take out a new loan from a bank to pay the transit cbill costs to get to the contract
- Contract salvage did NOT get set to 100%

Typo:

Image

Finances after the month rolled over once contract started, monthly pay deduction line highlighted:

Image

Salvage not set to 100%:

Image

### 3. Steps to Reproduce

Created new campaign and advanced days through Gray Monday

### Attach Files

[Gray Monday.zip](https://github.com/user-attachments/files/18737510/Gray.Monday.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.04-SNAPSHOT     Build Date: 2025-02-10T03:22:46.453971397

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Corrected a typo in the event message text ("contro" to "control") within the GrayMonday.properties file.
- Added `calculateContract` and set salvage percentage to 100% in Gray Monday contract logic.
- Removed unnecessary HTML tags in Gray Monday event messages to improve formatting.
- Updated text in event messages to no longer say that the player won't be paid, but that the pay will be very low.
- Updated `isGrayMonday` method to accept `LocalDate` and simulation flag directly, improving flexibility and reusability.
- Adjusted all `isGrayMonday` calls across the codebase to use the new parameters.
- Enhanced loan generation logic to incorporate Gray Monday event conditions, allowing for predatory loans.
- Improved documentation for `isGrayMonday` and loan-related methods to describe new parameters and behavior.

Fix #6017

### Dev Notes
The change to contracts from 'no pay' to 'very little pay' is a technical one. Basically, due to the interconnectivity of contract pay it's surprisingly difficult to just zero out a contract's pay without causing a bunch of weirdness. Instead, I lowered contract pay as much as possible. So the player will be getting a pittance.

Regarding loans. It was raised in the original bug report that loans were still available. Not removing loans was a conscious decision as I wanted the player to have a way out. However, it makes sense to change up the loan parameters so that the player forced to take a predatory loan (if they go that route) placing them in a very difficult position when combined with the other Gray Monday penalties.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/finances/Loan.java [hunk 1]
```diff
@@ -216,9 +218,38 @@ public boolean checkLoanPayment(final LocalDate today) {
...
+     * @return A {@link Loan} object representing the player's base loan terms based on
+     *         their rating and event conditions.
+     */
+    public static Loan getBaseLoan(final int rating, boolean simulateGrayMonday, final LocalDate date) {
         // we are going to treat the score from StellarOps the same as dragoons score
         // TODO: pirates and government forces
+
+        if (isGrayMonday(date, simulateGrayMonday)) {
+            // This simulates the player taking out a predatory loan
+            return new Loan(10000000, 70, 1, FinancialTerm.MONTHLY, 100, date);
```
Comment (Sleet01) [inline MekHQ/src/mekhq/campaign/finances/Loan.java:250]: :shark:

**Review by Sleet01 — APPROVED** [review]
Looks good!

File: MekHQ/src/mekhq/campaign/finances/Loan.java (hunk 1 above)
Comment (IllianiCBT) [reply MekHQ/src/mekhq/campaign/finances/Loan.java:250]: I'll have you know Bubba 'Kneecaps' Murphy is a reliable source of short-term C-Bills...

...just don't miss a payment...
