### PR TITLE
Fix #8376: Fixed Convoy Raid on Independent Command Rights Not Generating Loot if Player Has No Convoys

### LINKED ISSUE #8376: [Issue] Guerilla mission convoy raids do not give supplies.
### Brief Description *

Missions that say they give a supply cache fail to do so on guerrilla missions.

### 3. Steps to Reproduce

Load campaign, note total warehouse mass (7077.6 tons) auto complete the mission, say you captured all the tanks, compare to post mission warehouse.

### Attach Files

[Convoyraid.zip](https://github.com/user-attachments/files/23806348/Convoyraid.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.10 nightly 11-27

### Operating System *

Windows 11

### Java Version *

17.0.16

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #8376

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java [hunk 1]
```diff
@@ -197,7 +197,7 @@ public static void performResupply(Resupply resupply, AtBContract contract, int
         }
 
         // With the focus chosen, we determine the contents of the convoy
-        boolean isUsePlayerConvoy = resupply.getUsePlayerConvoy();
+        boolean isUsePlayerConvoy = !resupplyType.equals(RESUPPLY_LOOT) && resupply.getUsePlayerConvoy();
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java:200]: Something feels weird about how `resupplyType` is `final ResupplyType` that's gotten from `resupply` and how this is being checked. I feel like this should be a method in `Resupply` so we could just do `resupply.getUsePlayerConvoyButWithLootToo()` or whatever.
