### PR TITLE
1098: Fixing Repair Tab Tech Order Options Fix

### LINKED ISSUE #1098: Request for option in MegaMek HQ Tech assignments
Two parts:
First, when selecting techs to say, mothball or activate, it goes in order of tech assignment.  Is it possible to have Techs in that box ordered by *time*?
Second: in Repair Bay, same request, but leave 'assigned' tech on top, and also *leave* him on top til at no time left.  (Current behavior of Repair bay only puts the tech on top at once.)

I'm sure I'll have *more* requests over time...

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #1098 by adding the filterTechs() line.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/RepairTab.java [hunk 1]
```diff
@@ -830,9 +814,7 @@ public void refreshTechsList() {
         // The next gets all techs who have more than 0 minutes free, and sorted by skill descending (elites at bottom)
         List<Person> techs = getCampaign().getTechs(true);
         techsModel.setData(techs);
-        if ((selected > -1) && (selected < techs.size())) {
-            techTable.setRowSelectionInterval(selected, selected);
-        }
+        filterTechs();
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/RepairTab.java:817]: Only change for the bugfix. Sorry it isn't in its own commit, accidentally added them both together.

**Review by NickAragua — APPROVED** [review]
