### PR TITLE
Issues #2467, #3483: Fix Battle Armour Tech Introduction and Clan Filtering

### LINKED ISSUE #2467: 0.49.0-Dev: Can Acquire Clan Battle Armour Suits with Clan Acquisitions Turned Off
Campaign year is 2956. Planetary Acquisitions is enabled, with all clan options disabled. Further, clan part purchasing is disabled. However, I can still acquire the four BA suits shown in the below picture, and there are more on the list that are obviously Clan Battle Armour suits (Elemental or specific Clan Names).

image

image

[The Killing Kind29560730.cpnx.gz](https://github.com/MegaMek/mekhq/files/6136933/The.Killing.Kind29560730.cpnx.gz)

No custom units.

### LINKED ISSUE #3483: 0.49.10 Can buy BA suit not existing in current time
### Environment
I use MekHQ 0.49.10 with Java 11 on windows 10.

### Description
I can buy as part some battle armor suit who doesn't exist in the current years of my campaign, despite the use of the option parts/units limited by years.
BA suit procurement

As you can see, my campaign was in the year 3066 and I just bought an Amazon BA, which was created in 3101. I do the same thing with Dijnn and Se'irim, who were created in 3070 and 3072.

### Files
The files "BA acquisition.zip" is the save game.

[BA acquisition.zip](https://github.com/MegaMek/mekhq/files/9844864/BA.acquisition.zip)
[megamek.log](https://github.com/MegaMek/mekhq/files/9844866/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/9844867/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/9844868/mekhq.log)
[customs.zip](https://github.com/MegaMek/mekhq/files/9844872/customs.zip)

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #2467 and fixes #3483

### CODE REVIEW

File: MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java [hunk 1]
```diff
@@ -395,7 +395,7 @@ public boolean include(Entry<? extends PartsTableModel, ? extends Integer> entry
                         && !part.getName().toLowerCase().contains(txtFilter.getText().toLowerCase())
                         && !part.getDetails().toLowerCase().contains(txtFilter.getText().toLowerCase())) {
                     return false;
-                } else if ((part.getTechBase() == Part.T_CLAN)
+                } else if (((part.getTechBase() == Part.T_CLAN) || part.isClan())
```
Comment (SJuliez) [inline MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java:398]: Wow this tech base thing is confusing. In Part there's also:

isClanTechBase() {
        return getTechBase() == TECH_BASE_CLAN;
    }

But Im not much at home there so I'm going to assume this is all as it should be.

**Review by SJuliez — APPROVED** [review]

File: MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java (hunk 1 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java:398]: This is an area of the code I'm not the most at home with too, but the method is protected currently and I'd like to avoid changing most part code where possible.
