### PR TITLE
#3763 reversing quality names in unit set quality GM menu

### LINKED ISSUE #3763: [0.49.13] Wrong Quality names in Set Quality GM Menu after selecting reverse quality names in campaign settings.
Environment
[0.49.13] Mac Java Version: 16.0.2

### Description
While having reversed Quality unit parts on, manually setting them in GM mode shows the standard quality names. So setting a unit to quality F set it to A and accordantly for the other qualities. In the picture you can se the default sorting of the GM mode menu which has F as the highest, which equals to the highest quality set. 
 
image
[Quality names GM Mode wrong.cpnx.gz](https://github.com/MegaMek/mekhq/files/12707382/Quality.names.GM.Mode.wrong.cpnx.gz)

### PR DESCRIPTION
**Pull request by jackreichelt**
This fixes #3763. When setting the quality of a unit in the Hangar the quality names are properly reversed.

Code duplicated from [PartsTableMouseAdapter#actionPerformed](../blob/master/MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java#L107-L130)

### CODE REVIEW

**Comment by jackreichelt** [comment]
Just found that the quality names also need to reverse in the Campaign Options > Finances > Used Parts Value Multipliers. image

I'll look into this in a day or two.

**Comment by jackreichelt** [comment]
> Just found that the quality names also need to reverse in the Campaign Options > Finances > Price Multipliers > Used Parts Value Multipliers. image
> 
> I'll look into this in a day or two.

All done now.

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java [hunk 1]
```diff
@@ -176,43 +176,28 @@ public void actionPerformed(ActionEvent action) {
...
-                    break;
-                default:
-                    q = -1;
+            // TODO : Duplicated in PartsTableMouseAdapter#actionPerformed
+            int q = -1;
+            boolean reverse = gui.getCampaign().getCampaignOptions().isReverseQualityNames();
+            Object[] possibilities = { Part.getQualityName(Part.QUALITY_A, reverse),
+                Part.getQualityName(Part.QUALITY_B, reverse), Part.getQualityName(Part.QUALITY_C, reverse),
+                Part.getQualityName(Part.QUALITY_D, reverse), Part.getQualityName(Part.QUALITY_E, reverse),
+                Part.getQualityName(Part.QUALITY_F, reverse) };
```
Comment (rjhancock) [inline MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java:185]: Check the review guide as this is a little hard to read. Might need to put each quality on its own line to make reading it easier.

**Review by rjhancock — COMMENTED** [review]
Other than the one comment, just adding a flag for reversing of Quality names.

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java (hunk 1 above)
Comment (jackreichelt) [reply MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java]: Moved each to its own line. Also did this in `PartsTableMouseAdapter` where I copied this chunk from.

**Review by rjhancock — COMMENTED** [review]
Thank you, looks much better and easier to read.
