### PR TITLE
Fix #8226: Prevent HHWs from being crewed

### LINKED ISSUE #8226: [Issue] Certain HHW allow Crew Other to be assigned
### Brief Description *

Image

Image

As shown

### 3. Steps to Reproduce

_No response_

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

50.10

### Operating System *

Win11

### Java Version *

17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #8226 

Don't merge until MegaMek/megamek#7651 is merged.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java [hunk 1]
```diff
@@ -557,7 +557,6 @@ private UnitStatus processAlliedUnit(Entity e) {
      * <p>
      * This method should be run the first time an entity is loaded into the tracker, either from the game or from a MUL
      * file.
-     *
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java:560]: My whitespace, nooooo
