### PR TITLE
Fix #8428: It Is No Longer Possible to Jump Travel With Jump Incapable Units Such as Some Space Stations

### LINKED ISSUE #8428: [Issue] Able to jump with Space Station
### Brief Description *

Space station is behaving like a jumpship or warship by enabling jump.

Possible fix may be quite involved -- close to an RFE.

1. the simplest is simply prohibits jump until the player get rid of the space station.
2. the next possible solution is simply make the space station (and stuff loading on it) either unavailable, invisible, or both until the player returned to the system. Alternatively, make cargo onboard accessible but with latency -- i.e. interstellar shipping.
3. the most difficult would be to make an full instantiation of detached elements so potentially the player may operate on multiple system at the same time. 

### 3. Steps to Reproduce

1. create and crew space station, add to toe
2. travel to another system
3. 

### Attach Files

[customs.zip](https://github.com/user-attachments/files/23951967/customs.zip)

[yThe Reavers27851101.cpnx.gz](https://github.com/user-attachments/files/23951970/yThe.Reavers27851101.cpnx.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.10

### Operating System *

Windows 10

### Java Version *

Eclipse Adoptium 17.0.17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
## See Also [Task: Updated Description of K-F Adaptor & Modular Space Station Options](https://github.com/MegaMek/megameklab/pull/2091)

Fix #8428

If the player attempts to jump travel while the campaign contains non-jump capable units (such as damaged JumpShips or non-jump capable Space Stations) they will receive a blocker dialog. The player can cancel the jump, ignore the restriction (GM), or abandon the affected units.

If the player abandons or sells the affected units they will get a confirmation dialog to make sure they _really_ want to do that.

Mothballing the affected unit will **not** prevent this blocker.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/utilities/JumpBlockers.java [hunk 1]
```diff
@@ -0,0 +1,223 @@
...
+                if (jumpship.getDriveCoreType() == DRIVE_CORE_NONE) {
+                    nonJumpCapableUnits.add(unit);
+                    continue;
+                }
+
+                if (!jumpship.canJump()) {
+                    nonJumpCapableUnits.add(unit);
+                }
+            }
+        }
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/utilities/JumpBlockers.java:138]: Should we add `BuildingEntity` here - that'd be just "TO:AR Advanced Building" buildings. 

Your other option is `AbstractBuildingEntity` which includes `MobileStructure` entities too. I think those have nuance about if they can be transported, that's more up to you I think.

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/utilities/JumpBlockers.java:138]: I can do that, one moment

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/utilities/JumpBlockers.java:138]: Done
