### PR TITLE
Fix: Significantly Improved TO&E Reading Speed by Removing C3 Calculations

### LINKED ISSUE #6794: [Issue] [0.50.05] HQ hangs when opening TO&E tabs
### Brief Description *

When trying to open a force tab in the TO&E in my campaign, the game hangs for several minutes while my computers fans work hard. It does eventually expand the tab, but the issue repeats when I double-click to open one of that force's subforces.

This campaign file was imported from 50.03, had its settings updated according to the update instructions, was saved in 50.05, and was then reopened. This issue is occurring with the new save.

### 3. Steps to Reproduce

1. Open HQ file.
2. Go to TO&E tab.
3. Double-click on 12th Taskforce force tab.

### Attach Files

[battle_armor_maintenance_bug.zip](https://github.com/user-attachments/files/19930781/battle_armor_maintenance_bug.zip)
(Don't mind the file name, I found this issue while reporting a different bug.)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

0.50.05

### Operating System *

Windows 11

### Java Version *

Java Vendor: Eclipse Adoptium  Java Version: 17.0.14

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #6794

We previously received feedback from a user that C3 was not being factored into BV calculations in the TO&E tab. We then went in and fixed this, however that caused the every C3 equipped unit needing to read the ammo loadout of every unit in the TO&E any time the TO&E was interacted with. This resulted in a lock-up for large campaigns.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/view/ForceViewPanel.java [hunk 1]
```diff
@@ -182,16 +187,16 @@ private void fillStats() {
...
-
-            Unit u = campaign.getUnit(uid);
-            if (null != u) {
-                cost = cost.plus(u.getEntity().getCost(true));
-                ton += u.getEntity().getWeight();
-                String utype = UnitType.getTypeDisplayableName(u.getEntity().getUnitType());
+            Unit unit = campaign.getUnit(uid);
+            if (null != unit) {
+                // Never factor in C3 in this check. It will cause the TO&E to lock up for large campaigns.
+                bv += unit.getEntity().calculateBattleValue(true, !unit.hasPilot());
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/gui/view/ForceViewPanel.java:193]: Why do we need to calculate the entity's battle value every time? Could we just use the value from the entity's `getInitialBV()`? Could that be used in `force.getTotalBV(campaign, true)`?

Comment (Scoppio) [reply MekHQ/src/mekhq/gui/view/ForceViewPanel.java:193]: This could be cached.

**Review by Scoppio — APPROVED** [review]
I agree with the rollback, this is not the time for large refactors and redesigns for big problems.
