### PR TITLE
Fixed Force Commanders Changing on Load

### LINKED ISSUE #5304: V50.01 - Lance Commanders are not persisting upon loading of a save
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

image

Upon loading any save, MekHQ will revert any settings relative to the commander of a lance. Or will readjust even the default settings of the commander [highest rank]. As shown in the picture above, the commander of the first tank should be the lance commander as they are the only Sergeant in the lance, but instead the MekWarrior is set as the commander instead.

NOTE: This reversion happens even if you use the built in system of HQ to override the default commander.

### Steps to Reproduce

_No response_

### Operating System *

Windows 10

### Java Version *

V17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

V50.01

### Attach Files

[Issue Package.zip](https://github.com/user-attachments/files/18018025/Issue.Package.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by IllianiCBT**
Removed vestigial call to `updateCommander` when loading forces.

Renamed variables and parameters to improve readability and alignment with current coding standards. I was in that neck of the woods, so might as well.

Fixes #5304

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/force/Force.java [hunk 1]
```diff
@@ -763,19 +763,17 @@ public void writeToXML(PrintWriter pw1, int indent) {
...
                 }
             }
-            c.importForce(retVal);
+            campaign.importForce(force);
         } catch (Exception ex) {
             logger.error("", ex);
             return null;
         }
 
-        retVal.updateCommander(c);
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/force/Force.java:776]: This is the only functionality change.
