### PR TITLE
stratcon data/graphics fixes

### LINKED ISSUE #3741: 49.15 Nightly - Clicking on Contract Objective Facility Battle Causes NPE
Title.  Save and screen attached.  Scout top left of map with Charger Lance should reveal Facility.  Then click on it to assign a Lance to the battle and will get NPE.  Clicked through it and it allowed me to continue normally.  I fought the battle and destroyed all turrets and all but one enemy (More than 75%).  However, the Mech base stayed on the map.  It was my final contract objective and it did tick the objective off.  
Screenshot 2023-07-31 231911
Screenshot 2023-08-01 000239
[BaseNPE.zip](https://github.com/MegaMek/mekhq/files/12224899/BaseNPE.zip)

### PR DESCRIPTION
**Pull request by NickAragua**
In no particular order:

-fix missing badlands image
-don't fail to generate scenario when temperature mapping isn't present for facility
-more contrast between revealed/unrevealed hexes

fixes #3741

### CODE REVIEW

File: MekHQ/src/mekhq/gui/StratconPanel.java [hunk 1]
```diff
@@ -379,6 +379,12 @@ private boolean drawHexes(Graphics2D g2D, DrawHexType drawHexType) {
                         if (fogOfWarLayerImage != null) {
                             g2D.drawImage(fogOfWarLayerImage, null, graphHex.xpoints[1], graphHex.ypoints[0]);
                         }
+                        
+                        // needs a little more contrast between revealed and un-revealed hexes
+                        var push = g2D.getComposite();
+                        g2D.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, .5f));
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/StratconPanel.java:385]: Can we please use 0.5f for readability? The "." can be missed.

**Review by Windchild292 — APPROVED** [review]
Approved with a readability request
