### PR TITLE
Fix: #6780 `Armor::changeArmorAmount` and `Armor::getArmorAmount` consider all parts so more than one armor part is considered for repairs

### LINKED ISSUE #2942: [49.5] BAR armor conflicts with Standard armor
MekHQ 49.5
Win 10

I honestly don't know when this issue started, but I suspect it appeared when using 49.5 Nightlies (or 49.4 , when I started this particular campaign).
I have Standard armor and BAR armor (of various levels). When trying to repair mechs, I kept buying armor and the armor just wasn't adding up.

I have armor in the warehouse:
Screenshot 2021-11-07 014747

And it shows on the "Parts in use" window:
Screenshot 2021-11-07 014700

But in the repair dialog, it shows like this:
Screenshot 2021-11-07 014816
(that's the same amount as the BAR 5 armor)

The BAR armor can actually be used in repairs as Standard armor
If I sell the BAR armor, the Standard type starts showing up, but in a particular fashion: If I sell the 9 points of BAR 5, then Standard shows as 264, the value of BAR 6. When I sell all the BAR armor, the Standard one reappears in full. Further testing seems to show the problem goes away.

[Lisbon's Ravagers Repairs 3.cpnx.gz](https://github.com/MegaMek/mekhq/files/7491557/Lisbon.s.Ravagers.Repairs.3.cpnx.gz)
Save with more BAR 5 armor, allowing for repairs to be conducted:
[Lisbon's Ravagers Repairs.cpnx.gz](https://github.com/MegaMek/mekhq/files/7491569/Lisbon.s.Ravagers.Repairs.cpnx.gz)

Logs:
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7491558/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7491559/mekhqlog.txt)

To add that when you buy BAR armor, the "Parts in use" window doesn't update like with others:
Screenshot 2021-11-07 015227

### LINKED ISSUE #6780: Can't repair Armor Despite having Armor in Stock [Issue]
### Brief Description *

I have a bunch of new Armor in Stock but can't use it for repairs
I can use armor that I have picked up from Salvage

Image

Image

### 3. Steps to Reproduce

Was ok at first, but ran into not being able to replace armor when repairing

Image

### Attach Files

Image

[Can't repair armor.zip](https://github.com/user-attachments/files/19924525/Can.t.repair.armor.zip)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

0.50.05

### Operating System *

Windows 11

### Java Version *

jdk-17.0.14+7-jre

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
Fixes #6780 
Fixes #2942 

`Armor::changeArmorAmount` and `Armor::getArmorAmount` would both stop after getting the first part. If the warehouse has multiple parts of armor that are different quality, these methods would only consider/modify the first. Now it should properly consider all appropriate armors.

Wew this was a bit nastier than I wanted.

I want to whip up some unit tests, and run them against this before & after the change.

The "Removed" `public void changeAmountAvailable(int amount)` was just the overrides that were removed. If you need it deprecated it'll just be doing `super(amount)`, I don't see a need to explicitly have that when that's how it functions anyway.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java [hunk 1]
```diff
@@ -174,4 +159,23 @@ public TechAdvancement getTechAdvancement() {
         // type entry so we can just use the base protomek advancement
         return ProtoMek.TA_STANDARD_PROTOMEK;
     }
+
+    @Override
+    protected int changeAmountAvailableSingle(int amount) {
+        ProtoMekArmor a = (ProtoMekArmor) campaign.getWarehouse()
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java:165]: As we're editing these sections already, could we go through and remove the single letter variable names?

**Review by IllianiBird — APPROVED** [review]
LGTM

File: MekHQ/src/mekhq/campaign/parts/Armor.java [hunk 2]
```diff
@@ -572,31 +572,44 @@
...
+     * @param amount points of armor to add or remove
+     */
+    public void changeAmountAvailable(int amount) {
+        if (amount == 0) {
+            return;
+        }
 
-        return (a == null) ? 0 : a.getAmount();
-    }
+        int amountRemaining = amount;
```
[the remark this answers is not in the document]
Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/parts/Armor.java:599]: Done

File: MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java [hunk 3]
```diff
@@ -174,4 +159,23 @@
...
+        if (null != a) {
+            int amountRemaining = a.getAmount() + amount;
+            a.setAmount(amountRemaining);
+            if (a.getAmount() <= 0) {
+                campaign.getWarehouse().removePart(a);
+                return Math.min(0, amountRemaining);
+            }
+        } else if (amount > 0) {
+            campaign.getQuartermaster()
+                  .addPart(new ProtoMekArmor(getUnitTonnage(), type, amount, -1, isClanTechBase(), campaign), 0);
```
[the remark this answers is not in the document]
Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java]: Done

File: MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java (hunk 1 above)
Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java]: Yep, done!

File: MekHQ/src/mekhq/campaign/parts/Armor.java [hunk 4]
```diff
@@ -572,31 +572,44 @@ public boolean isEnoughSpareArmorAvailable() {
...
-                  .addPart(new Armor(getUnitTonnage(), type, amount, -1, false, isClanTechBase(), campaign), 0);
+
+        while ((amountRemaining != 0) && priorAmount != amountRemaining) {
+            priorAmount = amountRemaining;
+
+            amountRemaining = changeAmountAvailableSingle(amountRemaining);
+        }
+
+        if (amountRemaining > 0) {
+            logger.error("Still trying to add armor but that shouldn't have been a problem!");
```
Comment (Scoppio) [inline MekHQ/src/mekhq/campaign/parts/Armor.java:610]: logger.error should be restricted to only when you have an actual error that you can do something to fix, either because something really wrong happened, or because some data is corrupted, either is not the case, if this is a log that just works as a kind of `printf("<<<<<< HERE!!!")` then you should change the log level to `debug` or `trace`.

File: MekHQ/src/mekhq/campaign/parts/Armor.java [hunk 5]
```diff
@@ -572,31 +572,44 @@ public boolean isEnoughSpareArmorAvailable() {
...
+        } else if (amount < 0) {
+            logger.error("Still trying to remove armor but no more armor is in the warehouse!");
```
Comment (Scoppio) [inline MekHQ/src/mekhq/campaign/parts/Armor.java:612]: logger.error should be restricted to only when you have an actual error that you can do something to fix, either because something really wrong happened, or because some data is corrupted, either is not the case, if this is a log that just works as a kind of `printf("<<<<<< HERE!!!")` then you should change the log level to `debug` or `trace`.

File: MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java [hunk 6]
```diff
@@ -137,29 +137,14 @@ public Part getNewPart() {
...
-        } else if (amount > 0) {
-            campaign.getQuartermaster().addPart(new ProtoMekArmor(getUnitTonnage(), type, amount, -1, isClanTechBase(), campaign), 0);
-        }
+        return campaign.getWarehouse()
+                     .streamSpareParts()
+                     .mapToInt(part -> (part instanceof ProtoMekArmor protoMekArmor) &&
+                                             protoMekArmor.isPresent() &&
+                                             !protoMekArmor.isReservedForRefit() &&
+                                             isClanTechBase() == protoMekArmor.isClanTechBase() &&
+                                             (getType() == (protoMekArmor).getType()) ? protoMekArmor.getAmount() : 0)
```
Comment (Scoppio) [inline MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java:146]: the meaty part of it can me moved to a function (called isProtoMekArmor maybe?), this way you only needs to `streamSpareParts().filter(self::isProtoMekArmor).mapToInt(part::getAmount).sum()`

Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/parts/ProtoMekArmor.java:146]: Oh my gosh, that's perfect,thank you! I was struggling with finding a good way to handle that, I absolutely love it and can use this to clean this up even more.

**Comment by psikomonkie** [comment]
While working on unit tests today, I noticed `getAmountAvailable` wasn't working as expected for BAR Armor. If the bug in #2942 wasn't already fixed, it is now, and should be covered by Unit tests.
