### PR TITLE
Issue #2266: For LAMs check Landing Gear and Avionics when considering repairable slots

### LINKED ISSUE #2266: Cannot repair broken LAM
MekHQ 47.14

So I had a busted mothballed Phoenix Hawk LAM for a while and decided to repair it using recently gained funds.  It had a missing torso (and arm), no avionics and a few other minor things.

I repaired the armor and actuators just fine, but can't replace the torso. It asks to remove salvage parts, but the location has none. When I try to scrap the component, it scraps instead an equivalent part in the warehouse. GM mode doesn't allow me to repair this either.

I can, however, use the GM tools at the hangar tab and restore the unit, but even then I have to do it more than once to fully repair it. Breaking other Mechs with GM mode and repairing them out of it works just fine.

[mekhqlog.zip](https://github.com/MegaMek/megamek/files/5648078/mekhqlog.zip)
[megameklog.zip](https://github.com/MegaMek/megamek/files/5648079/megameklog.zip)

[Busted LAM.cpnx.gz](https://github.com/MegaMek/mekhq/files/5648091/Busted.LAM.cpnx.gz)
[Busted LAM after one(1) GM restore.cpnx.gz](https://github.com/MegaMek/megamek/files/5648081/Busted.LAM.after.one.1.GM.restore.cpnx.gz)
[customs.zip](https://github.com/MegaMek/megamek/files/5648083/customs.zip)

### PR DESCRIPTION
**Pull request by sixlettervariables**
This adds checks for Landing Gear and Avionics on LAMs when trying to fix missing parts. This fixes #2266.

I handle the following situations in this PR:
- Missing HD, RT, or LT: ensure that Avionics and Landing Gear (RT/LT only) have been removed first before replacing.
- Missing Avionics: ensure that the HD, RT, and LT are all present before replacing.
- Missing Landing Gear: ensure that the RT and LT are present before replacing.

TODO:
- [x] Unit tests

Missing RT and working Landing Gear:
image
image

Missing RT, missing Landing Gear, missing Avionics:
image
image

Replaced RT:
image

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/MissingAvionics.java [hunk 1]
```diff
@@ -75,6 +76,24 @@ public int getDifficulty() {
 
     @Override
     public String checkFixable() {
+        if ((unit != null) && (unit.getEntity() instanceof LandAirMech)) {
+            // Avionics are installed in the Head and both Torsos,
+            // make sure they're not missing.
+            for (Part part : unit.getParts()) {
```
Comment (NickAragua) [inline MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:82]: I don't suppose there's a better way to do this rather than looping through every part in the unit?

**Review by NickAragua — COMMENTED** [review]
One question, otherwise looks fine.

File: MekHQ/src/mekhq/campaign/parts/MissingAvionics.java (hunk 1 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/parts/MissingAvionics.java:82]: Not without a bit of work on `Unit` and I'm waiting til I have good tests for that.

**Comment by sixlettervariables** [comment]
@NickAragua fixed the conflicts (didn't see them on my phone)

**Review by NickAragua — APPROVED** [review]
