### PR TITLE
Fix #8179: Reduced Impact of Contract Breaches on Faction Standing; Added Falloff to Regard Changes from Contract Length

### LINKED ISSUE #8179: [Issue] (50.10 Nightly 14-11-2025) Possible faction standings tuning issue
### Brief Description *

Standing with MRB fell to -13 on a campaign with a single contract breach despite successful contracts otherwise.

### 3. Steps to Reproduce

_No response_

### Attach Files

[MHQ Faction Standings 16112025.zip](https://github.com/user-attachments/files/23573176/MHQ.Faction.Standings.16112025.zip)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

0.50.10 Nightly 14112025

### Operating System *

Win 11

### Java Version *

Eclipse Adoptium 17.0.14

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #8179

Contract Breach penalties were a little _too_ harsh, so they've been reduced.

The effects of contract length on regard delta were also not in the best of positions. These two could combine to create a really bad play experience if the player breached a very long contract (24 months, in the attached case). The effect of length now works logarithmically to effect a falloff, rather than being linear.

### CODE REVIEW

File: MekHQ/unittests/mekhq/campaign/universe/factionStanding/FactionStandingsTest.java [hunk 1]
```diff
@@ -166,47 +173,6 @@ void test_processAcceptContract_various(String testName, String primaryFaction,
...
-                    REGARD_DELTA_CONTRACT_PARTIAL_EMPLOYER),
-              Arguments.of("Mission Failed",
-                    MissionStatus.FAILED,
-                    10.0,
-                    REGARD_DELTA_CONTRACT_FAILURE_EMPLOYER),
-              Arguments.of("Mission Contract Breached",
-                    MissionStatus.BREACH,
-                    10.0,
-                    REGARD_DELTA_CONTRACT_BREACH_EMPLOYER));
-    }
```
Comment (IllianiBird) [inline MekHQ/unittests/mekhq/campaign/universe/factionStanding/FactionStandingsTest.java:187]: Removed this test battery as with the change in how regard is adjusted the test is no longer valid. I could update it but all we'd be testing for is if the hardcoded values got changed and I don't think that's valuable. Especially as this test would need to be fixed any time the hardcoded values got adjusted.

**Review by Sleet01 — APPROVED** [review]
LGTM
