### PR TITLE
Issue #2452: Ensure a Lance's Force assignment is still valid

### LINKED ISSUE #2452: Exception when AtB uses Lance out of sync with Campaign Forces
Exception from logs in #2435:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "mekhq.campaign.force.Force.isCombatForce()" because the return value of "mekhq.campaign.Campaign.getForce(int)" is null
	at mekhq.campaign.force.Lance.isEligible(Lance.java:230)
	at mekhq.campaign.mission.atb.AtBScenarioFactory.createScenariosForNewWeek(AtBScenarioFactory.java:210)
	at mekhq.campaign.Campaign.processNewDayATBScenarios(Campaign.java:3016)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3181)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3404)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$32(CampaignGUI.java:1053)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

_Originally posted by @sixlettervariables in https://github.com/MegaMek/mekhq/issues/2435#issuecomment-791970964_

### PR DESCRIPTION
**Pull request by sixlettervariables**
If the force assignment for a lance becomes out-of-sync, when AtB generates scenarios for the lance an NPE may be raised. `Lance::isEligible` presumes `Campaign::getForce` will be non-null for the assigned force. This resolves the NPE by instead marking the lance as ineligible if its force is no longer valid.

Ultimately, the entirety of Lance/Force/Scenario/Mission need to be converted to using object references to avoid these problems in the future.

Fixes #2452

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/force/Lance.java [hunk 1]
```diff
@@ -227,7 +227,8 @@ public int getWeightClass(Campaign c) {
 
     public boolean isEligible(Campaign c) {
         // ensure the lance is marked as a combat force
-        if (!c.getForce(forceId).isCombatForce()) {
+        final Force force = c.getForce(forceId);
+        if ((force == null) || !force.isCombatForce()) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/force/Lance.java:231]: Can we also annotate Campaign::getForce as having a nullable return? Would assist in preventing this in future.

**Review by Windchild292 — APPROVED** [review]
