### PR TITLE
Fix: Exclude unstreamlined DropShips from atmospheric StratCon scenarios

### LINKED ISSUE #6834: [Issue] Invalid Dropship assigned to planetary operations
### Brief Description *

The Behemoth dropship, and theoretically any dropship with Unstreamlined, should not be able to operate in atmosphere. MHQ still selects it for dropship defense type missions.

### 3. Steps to Reproduce

Have a behemoth.
Get a dropship defense mission.
Wonder how the heck you are going to launch

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

50.05

### Operating System *

Windows 3.2

### Java Version *

No coffee here

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by VicenteCartas**
## Summary

Unstreamlined DropShips (e.g., Behemoth) are no longer assigned to ground or low-atmosphere StratCon scenarios when the planet has atmosphere. They remain eligible for space scenarios and for operations on airless (vacuum) worlds.

## Changes

- `isValidUnitForScenario()` now receives `Campaign` and `MapLocation` parameters instead of just a boolean, enabling board-type and planetary condition checks
- Added generic board-type compatibility filtering using `doomedOnGround()` / `doomedInAtmosphere()` / `doomedInSpace()`
- Added specific filtering for the `unstreamlined` negative quirk, with a planet atmosphere lookup to allow operations on vacuum worlds
- Changed method visibility from `private` to package-private for testability
- Added 8 unit tests covering all branches of the new validation logic

Fixes #6834

Companion PR: MegaMek/mm-data#315 (adds missing `unstreamlined` quirk to Behemoth data files)

### CODE REVIEW

**Comment by VicenteCartas** [comment]
@SJuliez This is the fix for the atmospheric operations, but in MekHQ instead, so we can check for vacuum.

**Comment by binaryspica** [comment]
Would it only checks for Un-streamlined design quirk? It is usually said that Mammoth(52,000 tons) is the upper limit of the dropship that could enter atmosphere then go back to the space - although there is no nailed rules for this but it is the well known theory in Battletech universe. And for now Behemoth of MegaMek data lacks Un-streamlined design quirk, so if you only count for the quirk then those dropships are still chosen on the missions.

Thus, I think that it's safe that any dropships with 52,100 tons or more are need to be checked as well. Else is MegaMek already checks that those dropships are unfit for the atmosphere insertion and the addition to the checking for the weight is not required at all?

Edit: Also too slow dropships are must be excluded as well, for if I remember correctly you need at least thrust point of 4 to back to the space, so unless the dropship is bounded to the specific planet then it must not enter the atmosphere if it can't make thrust point of 4 or more.

Still, if make it easier then manually add anything with unfit for the ground duty Un-streamlined design quirk is a solution, though.

File: MekHQ/src/mekhq/campaign/stratCon/StratConRulesManager.java [hunk 1]
```diff
@@ -1006,24 +1009,49 @@ private static Collection<Unit> findPotentialUnits(Campaign campaign, int explic
...
+        }
+
+        // Unstreamlined units (e.g. Behemoth) cannot operate in atmosphere or on the ground,
+        // but they can operate on airless worlds (vacuum)
+        if (isAtmospheric && entity.hasQuirk(OptionsConstants.QUIRK_NEG_UNSTREAMLINED)) {
+            Planet planet = campaign.getLocation().getPlanet();
+            if (planet == null || !planet.getAtmosphere(campaign.getLocalDate()).isNone()) {
+                return false;
+            }
+        }
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/stratCon/StratConRulesManager.java:1051]: The logic for unstreamlined (and other non-atmospheric capable Aeros) should probably live in MegaMek and not MekHQ. I believe PlanteraryConditions will be what you'll want to look for on the MM side for this. 


EDIT: `PlanetaryConditions::whyDoomed` looks interesting.

Comment (VicenteCartas) [reply MekHQ/src/mekhq/campaign/stratCon/StratConRulesManager.java:1051]: I tried that first :)

https://github.com/MegaMek/megamek/pull/8183

@SJuliez made a good point about this that checking for atmosphere is not that easy on the Megamek side doomed functions.

I could reopen the original megamek PR and leave the comment there that vacuum is not taken into account, or try to figure out a different way to handle it on the megamek side (I haven't looked a lot at the megamek code).

**Comment by gsparks3** [comment]
> Would it only checks for Un-streamlined design quirk? It is usually said that Mammoth(52,000 tons) is the upper limit of the dropship that could enter atmosphere then go back to the space - although there is no nailed rules for this but it is the well known theory in Battletech universe. And for now Behemoth of MegaMek data lacks Un-streamlined design quirk, so if you only count for the quirk then those dropships are still chosen on the missions.
> 
> Thus, I think that it's safe that any dropships with 52,100 tons or more are need to be checked as well. Else is MegaMek already checks that those dropships are unfit for the atmosphere insertion and the addition to the checking for the weight is not required at all?
> 
> Edit: Also too slow dropships are must be excluded as well, for if I remember correctly you need at least thrust point of 4 to back to the space, so unless the dropship is bounded to the specific planet then it must not enter the atmosphere if it can't make thrust point of 4 or more.
> 
> Still, if make it easier then manually add anything with unfit for the ground duty Un-streamlined design quirk is a solution, though.

There are zero canon DS above 52,000 tons that _don't_ have Un-Streamlined quirk (and very few such DS period; there's only the Castrum and some Behemoth variants). Also, AFAIK that 52,000 ton limit is currently fluff, not a gameplay rule, and therefore potentially subject to change should new DS be introduced. 

Similarly, there are zero canon DS besides the Behemoth that do not have at least 3 Safe Thrust (and therefore 5 Maximum Thrust). The requirement for 4 Thrust is actually to _leave_ the atmospheric interface (see Total Warfare page 79); aerospace units with less than 4 Thrust available are still capable of atmospheric flight, or even atmospheric reentry _from_ space if desired. The requirement discussed on that page is also plausibly meant for "in the heat of combat" situations, given that any craft capable of continuous 1g thrust should be able to reach orbit _eventually_.

As such, nothing mentioned in the quoted post is an issue.

**Review by Sleet01 — APPROVED** [review]
This looks fine to me.
It would be ideal if we could rely on MegaMek but it makes sense to also check within MHQ first.
