### PR TITLE
Fix #7831: Fixed Parts in Use Not Detecting Units; Refactored Parts in Use Out of Campaign.java

### LINKED ISSUE #7831: [Issue] [0.50.10-nightly-2025-10-25] requested stock levels broken
### Brief Description *

in the latest nightly, 'order stock' and 'add stock' to requested levels aren't doing anything, and the weekly check is reporting nothing needs stock. this is in a fresh campaign with the to&e filled out with the company generator and a few extras.

### 3. Steps to Reproduce

1. load the attached campaign
2. attempt to order or gm-add requested stock levels
3. observe nothing is added to the shopping list

### Attach Files

[logs.zip](https://github.com/user-attachments/files/23142076/logs.zip)

[Autosave-1-The 20th Cossacks-31510114.cpnx.gz](https://github.com/user-attachments/files/23142084/Autosave-1-The.20th.Cossacks-31510114.cpnx.gz)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

0.50.10-nightly-2025-10-25

### Operating System *

windows 10

### Java Version *

    Java Vendor: Eclipse Adoptium     Java Version: 17.0.15

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #7831

Primarily the goal of this PR is to fix parts in use incorrectly excluding parts on units (whoops). While I was there I also did two big changes:

- Parts in Use no longer lives in Campaign. It living in Campaign was an old design choice, where anything that might possibly relate to Campaign got dumped there. This kind of thinking is why we've ended up with such a bloated Campaign class. Moving Parts in Use into its own dedicated class is the right move. No major code changes were made (outside of fixing the above cited bug).
- I spotted a TODO from @psikomonkie asking for `getWarehouse().getQuantity(Part)` to be relocated into `Part` itself. This PR does that.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/Part.java [hunk 1]
```diff
@@ -1441,6 +1450,47 @@ public boolean isSpare() {
...
+     *       quantity
+     */
+    public int getQuantityForPartsInUse() {
+        if (!isSparePartInUse()) {
+            return 0;
+        }
+
+        return (this.getUnit() != null) ? 1 : this.getQuantity();
+    }
+
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/parts/Part.java:1494]: The introduction (and integration) of these two methods are the only changes of substance. The rest is existing code that's been moved around and refactored.

File: MekHQ/src/mekhq/campaign/Warehouse.java [hunk 2]
```diff
@@ -343,41 +343,23 @@ public List<Part> getSpareParts() {
...
+        if (p instanceof Armor) {
+            return ((Armor) p).getAmount();
         }
-        if (part instanceof AmmoStorage) {
-            return ((AmmoStorage) part).getShots();
+        if (p instanceof AmmoStorage) {
+            return ((AmmoStorage) p).getShots();
         }
-        return (part.getUnit() != null) ? 1 : part.getQuantity();
+        return (p.getUnit() != null) ? 1 : p.getQuantity();
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/Warehouse.java]: This TODO has been resolved.

File: MekHQ/src/mekhq/campaign/market/PartsInUseManager.java [hunk 3]
```diff
@@ -0,0 +1,467 @@
...
+     * The values for each part type are retrieved from the campaign options.</p>
+     *
+     * @param part The {@link Part} for which the default stock percentage is to be determined. The part must not be
+     *             {@code null}.
+     *
+     * @return An {@code int} representing the default stock percentage for the given part type, as defined in the
+     *       campaign options.
+     */
+    private int getDefaultStockPercent(Part part) {
+        if (part instanceof HeatSink) {
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/market/PartsInUseManager.java:168]: Existing code

File: MekHQ/src/mekhq/campaign/parts/Armor.java [hunk 4]
```diff
@@ -588,6 +588,15 @@ public double getArmorPointsPerTon() {
...
     }
 
+    @Override
+    public int getQuantityForPartsInUse() {
+        if (isSparePartInUse()) {
+            return 0;
+        }
+
+        return this.getAmount();
+    }
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/Armor.java:598]: Fixed

File: MekHQ/src/mekhq/campaign/parts/AmmoStorage.java [hunk 5]
```diff
@@ -133,6 +133,15 @@ public int getSellableQuantity() {
...
     }
 
+    @Override
+    public int getQuantityForPartsInUse() {
+        if (isSparePartInUse()) {
+            return 0;
+        }
+
+        return this.getShots();
+    }
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/AmmoStorage.java:143]: fixed

File: MekHQ/src/mekhq/campaign/parts/Part.java [hunk 6]
```diff
@@ -1441,6 +1450,47 @@ public boolean isSpare() {
...
+     * @return {@code 0} if the part is available as a spare, {@code 1} if assigned to a unit, otherwise the part's
+     *       quantity
+     */
+    public int getQuantityForPartsInUse() {
+        if (!isSparePartInUse()) {
+            return 0;
+        }
+
+        return (this.getUnit() != null) ? 1 : this.getQuantity();
+    }
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/Part.java:1493]: Hallucination

File: MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java [hunk 7]
```diff
@@ -0,0 +1,735 @@
...
+
+                // Assert
+                assertEquals(FIRST_DESIRED_STOCK, firstStockLevel);
+                assertEquals(SECOND_DESIRED_STOCK, secondStockLevel);
+            }
+        }
+
+        /**
+         * {@link Campaign#getDefaultStockPercent} is private, so we'll need to use reflection to get the method for
+         * testing
```
Comment (psikomonkie) [inline MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java]: This should probably be updated to `{@link PartsInUseManager#getDefaultStockPercent}`

Also at line 308, etc.

File: MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java [hunk 8]
```diff
@@ -0,0 +1,735 @@
...
+
+        @Nested
+        public class TestAutoLogisticsCampaignOptions {
+            final static int FIRST_DESIRED_STOCK = 100;
+            final static int SECOND_DESIRED_STOCK = 200;
+
+            @BeforeEach
+            public void beforeEach() {
+                // beforeEach MUST refresh Campaign Options!
+                campaign = MHQTestUtilities.getTestCampaign();
```
Comment (psikomonkie) [inline MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java]: How does this impact the performance? This was originally in `beforeAll()` because it takes a long time to initialize, and it doesn't need to be reinitialized each time we run a test.

File: MekHQ/src/mekhq/campaign/Warehouse.java [hunk 9]
```diff
@@ -343,41 +343,23 @@ public List<Part> getSpareParts() {
...
-    public int getPartQuantity(Part part, boolean sparesOnly) {
-        //TODO: getPartQuantity should be an overloaded method in Part.java, I'm just getting it out of campaign
-        if (sparesOnly && !part.isSpare()) {
-            return 0;
-        }
-
-        if (part instanceof Armor) {
-            return ((Armor) part).getAmount();
+    @Deprecated(since = "0.50.10", forRemoval = true)
+    public int getPartQuantity(Part p) {
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/Warehouse.java]: I don't think this should be marked as deprecated if we're also changing the signature. I think we should either leave the original signature and mark it deprecated, or remove it all together.

File: MekHQ/src/mekhq/campaign/parts/Part.java [hunk 10]
```diff
@@ -1441,6 +1450,47 @@ public boolean isSpare() {
...
+     * </ul>
+     *
+     * @return {@code true} if this part is available for use as a spare, {@code false} otherwise
+     *
+     * @author Illiani
+     * @since 0.50.10
+     */
+    public boolean isSparePartInUse() {
+        return (parentPart == null) && (refitUnit == null) && (reservedBy == null);
+    }
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/parts/Part.java:1473]: It took me a minute to understand this method, I think it should maybe be renamed. 

It looks like this method is only used as `!isSparePartInuse`. I think this might be better suited as `isPartUsedOrReserved` that returns `!((parentPart == null) && (refitUnit == null) && (reservedBy == null))`

File: MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java (hunk 8 above)
Comment (IllianiBird) [reply MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java]: According to Sleet this shouldn't be an issue any more - your original tests predate our new testable campaign code changes that were made during your hiatus.

File: MekHQ/src/mekhq/campaign/parts/Part.java (hunk 10 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/Part.java:1473]: Great suggestion

File: MekHQ/src/mekhq/campaign/Warehouse.java (hunk 9 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/Warehouse.java]: Done

File: MekHQ/src/mekhq/campaign/parts/Part.java (hunk 10 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/Part.java:1473]: Done

File: MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java (hunk 8 above)
Comment (IllianiBird) [reply MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java]: That said, there is literally no reason not to use a single instance throughout. Updated to move campaign back into before all

File: MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java (hunk 7 above)
Comment (IllianiBird) [reply MekHQ/unittests/mekhq/campaign/market/PartsInUseManagerTest.java]: Done, though I had to use code rather than link due to some weird accessibility issues
