### PR TITLE
Fix: #6782 Fixed Campaign Summary Displays of Kitchen Capacity and Injured Personnel

### LINKED ISSUE #6782: [50.05] Warning symbol on Kitchens while (x/y) x is smaller than y.
### Brief Description *

Image

As title, kitchen is reporting a warning, no hoverable text to denote warning reason.

This save does have custom units that were made to have field kitchens. (Dropships)

### 3. Steps to Reproduce

_No response_

### Attach Files

[mekfiles.zip](https://github.com/user-attachments/files/19924854/mekfiles.zip)

[Valkyrie Legion30420425.cpnx.gz](https://github.com/user-attachments/files/19924856/Valkyrie.Legion30420425.cpnx.gz)

[logs.zip](https://github.com/user-attachments/files/19924859/logs.zip)

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

0.50.05

### Operating System *

Windows 11

### Java Version *

17.0.12.7

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #6782

### Dev Notes
The check for whether kitchens were in capacity had managed to get inverted at some point, causing the Campaign Summary pane to display incorrect information.

Furthermore, the number of injured personnel was malformed, causing all personnel to display as injured.

Both issues have now been fixed.

### CODE REVIEW

**Comment by IllianiBird** [comment]
I think this should be in 50.06 because it addresses an issue with fatigue recovery and also is a visual bug we've had a couple of user queries about over on Discord.

File: MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java [hunk 1]
```diff
@@ -143,7 +148,7 @@ public static int checkFieldKitchenUsage(List<Person> activePersonnel, boolean i
      * @return {@code true} if the available capacity is sufficient; {@code false} otherwise.
      */
     public static boolean areFieldKitchensWithinCapacity(int fieldKitchenCapacity, int fieldKitchenUsage) {
-        return fieldKitchenCapacity <= fieldKitchenUsage;
+        return fieldKitchenCapacity >= fieldKitchenUsage;
```
Comment (Scoppio) [inline MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java:151]:
```suggestion
        return fieldKitchenCapacity > fieldKitchenUsage;
```
I believe that it should only not be within capacity once larget than, not larger or equals to.

**Review by Scoppio — CHANGES_REQUESTED** [review]

File: MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java (hunk 1 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java:151]: No, larger than or equal to is correct. If you have 5 capacity you're still within capacity if you have 5 consumption.

**Review by Scoppio — APPROVED** [review]
