### PR TITLE
Fixed MekHQ Throwing Meks into Low Altitude Scenarios

### LINKED ISSUE #6315: Air Convoy Intercept Scenario - Meks assigned with low atmo map.
### Brief Description *

When an air convoy & separate mek lance is active on the TOE, and an convoy intercept scenario happens, a low atmosphere map get assigned the scenario.... But so does a mek lance, which don't operate in low atmosphere.  I'm unable to undeploy the meks (presumably because the command rights are "integrated").  

### 3. Steps to Reproduce

- Command a company under a specific house (I believe this makes missions mostly or all integrated?)
- Obtain dropship with cargo space
- Assign dropship to a convoy in TOE
- Also have aMek lance active in TOE
- Accept Mission where support/convoy runs will occur
- Convoy event occurs
- Interception scenario occurs

### Attach Files

[convoy_low_atmo_meks.zip](https://github.com/user-attachments/files/19376997/convoy_low_atmo_meks.zip)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

0.50.03

### Operating System *

Windows 11

### Java Version *

21.0.6

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Moved VTOL and aerial force utility methods from `ResupplyUtilities` to the `Force` class for better cohesion and encapsulation.
- Replaced `Campaign` references with `Hangar` in force resolution methods to improve decoupling and maintainability.
- Simplified deployment logic and aerial/VTOL determination logic in relevant classes by centralizing functionality in `Force`.
- Updated force sorting logic to improve handling of map types, including better differentiation for airborne and aerospace forces.
- Enhanced error handling to log missing force entries when accessing by ID.

Fix #6315

### Dev Notes
This does three things:
- It moves the various 'does this force contain x' utility methods out of resupplies and into force, so they're more accessible. It also tidies them up a bit so they're more universally useful, rather than being specific to resupply's use case.
- It addresses uses of 'primary unit type', when determining interception scenario type, to instead use the above utility methods so that we're ensuring that forces can only be deployed to scenarios where all units in the force are appropriate for that map type.
- It also updates how we handle Integrated contracts to use the same checks and balances. This will remove the risk we previously had where if a force contains a majority of aerospace units, but also contained a couple of meks (or conventional fighters) the force could still be deployed to a Space scenario with predictably disastrous results.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/force/Force.java [hunk 1]
```diff
@@ -1123,4 +1126,132 @@ private static int populateOriginNode(Campaign campaign, Force origin) {
 
         return origin.getFormationLevel().parseToInt();
     }
+
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/force/Force.java:1129]: These are the three utility methods that got moved out of Resupply

File: MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java [hunk 2]
```diff
@@ -1889,39 +1897,73 @@ private static boolean commanderLanceHasDefensiveAssignment(AtBDynamicScenario s
...
+     * @param forceIDs  A list of force IDs to classify.
+     * @param hangar    The {@link Hangar} instance containing aerial or aerospace-related information
+     *                  about forces.
+     * @param allForces A pre-resolved list of {@link Force} objects. Forces are accessed using their
+     *                  IDs as indices, providing performance benefits when compared to fetching forces
+     *                  on demand.
+     * @return A {@link Map} where each {@link MapLocation} key corresponds to a map type, and the value
+     *         is a list of force IDs that can operate in that map type.
+     */
+    public static Map<MapLocation, List<Integer>> sortForcesByMapType(List<Integer> forceIDs,
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java:1931]: This is the method that was fundamentally changed to facilitate the updated force assignment stuff.

File: MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java [hunk 3]
```diff
@@ -1679,41 +1682,46 @@ public static ReinforcementResultsType processReinforcementDeployment(Force forc
...
-     *         or a default template if no specific case is matched.
-     * @see ScenarioTemplate#Deserialize(String)
-     */
-    private static ScenarioTemplate getInterceptionScenarioTemplate(Force force, Campaign campaign) {
+     *                 The force composition is used to determine the appropriate scenario template.
+     * @param hangar   The {@link Hangar} instance from which to retrieve the {@link Unit}.
+     * @return A {@link ScenarioTemplate} instance representing the chosen scenario template file based
+     *         on the logic described, or a default template if no special conditions are satisfied.
+     */
+    private static ScenarioTemplate getInterceptionScenarioTemplate(Force force, Hangar hangar) {
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java:1705]: This method was also fundamentally changed.

File: MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java [hunk 4]
```diff
@@ -1889,39 +1897,73 @@ private static boolean commanderLanceHasDefensiveAssignment(AtBDynamicScenario s
...
+                continue;
             }
+
+            airborneOnly = force.forceContainsOnlyAerialForces(hangar, false,
+                  false);
+
+            aerospaceOnly = false;
+            if (airborneOnly) {
+                aerospaceOnly = force.forceContainsOnlyAerialForces(hangar, false,
+                      false);
```
Comment (Sleet01) [inline MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java:1956]: I think this should be called with `hanger, false, true` to exclude Conventional Fighters, yes?

File: MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java [hunk 5]
```diff
@@ -1679,41 +1682,46 @@ public static ReinforcementResultsType processReinforcementDeployment(Force forc
...
+              false);
 
-        if ((primaryUnitType == CONV_FIGHTER)
-            || (primaryUnitType == AEROSPACEFIGHTER) && (randomInt(3) == 0)) {
-            scenarioTemplate = ScenarioTemplate.Deserialize(String.format(templateString, "Low-Atmosphere "));
-        } else if (primaryUnitType >= AEROSPACEFIGHTER) {
+        boolean aerospaceOnly = false;
+        if (airborneOnly) {
+            aerospaceOnly = force.forceContainsOnlyAerialForces(hangar, false,
+                  false);
```
Comment (Sleet01) [inline MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java:1716]: This should probably also be `hanger, false, true` if I'm reading the intent and function correctly.

File: MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java (hunk 4 above)
Comment (IllianiCBT) [reply MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java:1956]: Exactly right, lemme correct that

**Review by Sleet01 — CHANGES_REQUESTED** [review]
I think a couple of calls to forceContainsOnlyAerialForces need the last argument switched to `true` to exclude CFs.

**Comment by IllianiCBT** [comment]
- Updated `forceContainsOnlyAerialForces` method calls to pass `true` instead of `false` for consistent aerospace validation.

**Review by Sleet01 — APPROVED** [review]
All good!
