### PR TITLE
Issue #2248: Fix various ContractMarket exceptions when operating at the bounds of MekHQ data

### LINKED ISSUE #2248: Monthly Date Rollover Error - No Unit Market or Contract Info
### Environment
What version of MekHQ does your issue apply to? 0.47.14
What operating system are you using?  Windows
What java version are you using?  Java version 1.8.0_271

### Description
Though working way outside the normal scope of MekHQ, I've snagged a bug where the date sticks at the end of the month (which I know is a repeat), the unit market is blank, and the contract market is blank. Also, there is no roll for procuring parts even though there should be.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5618710/mekhqlog.txt)
[BS_Brigade.cpnx.gz](https://github.com/MegaMek/mekhq/files/5618711/BS_Brigade.cpnx.gz)

[Ticket.zip](https://github.com/MegaMek/mekhq/files/5618713/Ticket.zip)

### PR DESCRIPTION
**Pull request by sixlettervariables**
The AtB Contract Market does not enjoy being at the bounds of playable data. This PR just adds a few checks to have it more gracefully fail instead of throwing exceptions and blocking the campaign's forward progress. This sort of fixes #2248 at a wishy-washy level.

### CODE REVIEW

**Comment by sixlettervariables** [comment]
Example warning messages from this PR:
```
17:01:58,391 WARN [mekhq.campaign.market.ContractMarket] {AWT-EventQueue-0} 
generateAtBContract(), line 320 : Could not generate an AtB Contract because there was no employer!

17:03:21,470 WARN [mekhq.campaign.market.ContractMarket] {AWT-EventQueue-0} 
generateContractOffers(), line 209 : Unable to find any factions around Terra on 2045-12-01
```

File: MekHQ/src/mekhq/campaign/market/ContractMarket.java [hunk 1]
```diff
@@ -182,7 +189,7 @@ public void generateContractOffers(Campaign campaign, boolean newCampaign) {
                         inBackwater = false;
                     }
                 }
-            } else {
+            } else if (currentFactions.size() > 0) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/market/ContractMarket.java:192]: Why > 0 instead of == 0?

File: MekHQ/src/mekhq/campaign/market/ContractMarket.java [hunk 2]
```diff
@@ -314,8 +335,16 @@ private AtBContract generateAtBContract(Campaign campaign, String employer, int
 
         if (employer.equals("MERC")) {
             contract.setMercSubcontract(true);
-            while (employer.equals("MERC")) {
+            for (int attempts = 0; attempts < MAXIMUM_ATTEMPTS_TO_FIND_NON_MERC_EMPLOYER; ++attempts) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/market/ContractMarket.java:338]:
```suggestion
            for (int attempts = 0; attempts < MAXIMUM_ATTEMPTS_TO_FIND_NON_MERC_EMPLOYER; attempts++) {
```

Comment (Windchild292) [reply MekHQ/src/mekhq/campaign/market/ContractMarket.java:338]: more standard format

**Review by Windchild292 — APPROVED** [review]
Pending LGTM fixes

File: MekHQ/src/mekhq/campaign/market/ContractMarket.java (hunk 1 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/market/ContractMarket.java:192]: This case is for at least one faction. The above case is for more than one.

Comment (Windchild292) [reply MekHQ/src/mekhq/campaign/market/ContractMarket.java:192]: Sorry, the latter should have been == 1

Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/market/ContractMarket.java:192]: I noticed the static analysis tools we use have problems with ranges mixed with (in)equality and did much better with ranges alone. I believe it was elsewhere with target rolls.

**Comment by sixlettervariables** [comment]
I tried adding unit tests but ContractMarket makes too much usage of static classes.
