### PR TITLE
Fix #8177: Prevent Hard Lock When Over Salvage % in Salvage Picker

### LINKED ISSUE #8177: [Issue]Salvaging too much using CAMOPS salvage in one mission results in unprogressable salvage screen in the next mission
### Brief Description *

If you go over your salvage share  in one mission, and the next mission does not have enough salvage to get you back under your % split, you can't advance past the salvage screen during the mission resolution dialogue even if all vehicles are assigned and you leave everything to your employer by claiming nothing.

### 3. Steps to Reproduce

1.  Win a fight where you go over your salvage % a fair amount by salvaging a big mech.
2.  Start another fight where if you win you get salvage.  But the opfor is small.
3. Win but accidentally chain detonate the ammo in one of the two units you're fighting.
4. KO the other pilot and /victory (his machine is down a leg so it's not going anywhere)
5. The value of the remaining unit is not enough to bring you back under your % (60 in this case)
6. Even if you don't claim this one unit the salvage screen won't let you progress.
7. Have to forcequit to do anything.

### Attach Files

[Cupcake's Inferno Legion30270501-5.cpnx.gz](https://github.com/user-attachments/files/23572656/Cupcake.s.Inferno.Legion30270501-5.cpnx.gz)

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

MekHQ v0.50.10-nightly-2025-11-16

### Operating System *

Win 11

### Java Version *

Eclipse Adoptium     Java Version: 17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #8177

I have no idea how the user reached a point where they _were_ over their % allowance, but this PR at least stops that turning into a hard lock.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/dialog/camOpsSalvage/SalvagePostScenarioPicker.java [hunk 1]
```diff
@@ -785,7 +785,9 @@ private void updateConfirmButtonState(List<SalvageComboBoxGroup> salvageComboBox
 
                 if (currentPercent.compareTo(BigDecimal.valueOf(salvagePercent)) > 0 && !isExchangeRights) {
                     disableConfirmAndColorName(confirmButton, unitSalvageLabel);
-                    shouldEnable = false;
+
+                    // If we've gone over our %, we only block progression if the player is trying to salvage even more.
+                    shouldEnable = !unitSalvageMoneyCurrent.equals(unitSalvageMoneyInitial);
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/gui/dialog/camOpsSalvage/SalvagePostScenarioPicker.java:790]: This is the only functionality change. The rest is me relocating the various salvage dialogs into their own folder.
