### PR TITLE
Fix #8460: Fixed Transport Cost Calculations Not Correctly Tracking Fixed Wing Support Units

### LINKED ISSUE #8460: fixed wing support vehicles and conventional fighters not getting assigned bays for transport
### Brief Description *

0.50.10

Having loaded several dropships with a variety of transport bays I checked the jump fee summary and noticed every fixed wing support craft available in 2866 was requiring that I rent a "misc unit bay". I had a custom conventional fighter as well that did not require a misc unit bay but when checking the transport capacity report not a single bay had been occupied despite having a "Union (2708)", a "Union (2709) (Combined Arms) MkII", and an "Achilles (2582)". Not only was no bay occupied but the report also claimed there were no units not transport save for the dropships.

### 3. Steps to Reproduce

to recreate my testing

1 start a new campaign on january 1st 2866 with the new player preset
2 GM add enough dropships to get every bay I thought the units might occupy
         "Union (2708)"
         "Union (2709) (Combined Arms) MkII"
         "Achilles (2582)"
3 GM add everything available under the "conventional fighter" unit type
4 Check the jump fee summary report and transport capacity report after adding all units
5 Remove one conventional fighter at a time checking the same reports after each craft and compare the stats from the reports with the number of units in the hangar

attached is a zipped folder containing the only custom unit used during testing and the logs from my testing just before posting the issue

### Attach Files

[custom.zip](https://github.com/user-attachments/files/24088161/custom.zip)

[unified_log_20251210_4.log.gz](https://github.com/user-attachments/files/24088175/unified_log_20251210_4.log.gz)
[unified_log_20251210_5.log.gz](https://github.com/user-attachments/files/24088176/unified_log_20251210_5.log.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.10

### Operating System *

Windows 11

### Java Version *

Java Vendor: Oracle Corporation       Java Version: 17.0.12

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #8460

The transport cost calculator now correctly places Fixed-Wing Support units into ASF bays.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/mission/TransportCostCalculations.java [hunk 1]
```diff
@@ -726,7 +726,9 @@ void countUnitsByType() {
                     smallCraftCount++;
                 } else if (entity.isMek()) {
                     mekCount++;
-                } else if (entity.isAerospaceFighter() || entity.isConventionalFighter()) {
+                } else if (entity.isAerospaceFighter() ||
+                                 entity.isConventionalFighter() ||
+                                 entity.isFixedWingSupport()) {
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/mission/TransportCostCalculations.java:731]: Can a 200 ton fixed wing support fit into a 150 ton ASF bay, or do they need to be tracked separately? Lines 709 and 721 imply that they should be tracked separately (that these are grouped by how they're transported).

Comment (HammerGS) [reply MekHQ/src/mekhq/campaign/mission/TransportCostCalculations.java:731]: I think its covered here. https://battletech.com/forums/index.php?topic=55993.0

The transport rules in TechManual and Tactical Operations group bays by the type of unit they are designed to carry, not just by tonnage. Because of this, you do not “overflow” a larger FWSV into an ASF bay even if the latter has nominal tonnage available.

Comment (gsparks3) [reply MekHQ/src/mekhq/campaign/mission/TransportCostCalculations.java:731]: Anything above 100t would have to use a small craft bay. CFs can't go above 50t, so those always fit in fighter bays.
