### PR TITLE
Addition of a new AmmoType equals method that only compares AmmoType …

### LINKED ISSUE #1665: Campaign Option>Tech Limits>Use ammo by type (unofficial) does not seem to work
Campaign Options > Tech Limits > Use ammo by type (unofficial), ie being able to load an LRM 5 with LRM20 ammo, is not working.

### Environment
47.5 has  been tested and it's not working. It's not working on 46.0 either 

### Description
image
image
image

### PR DESCRIPTION
**Pull request by ChaoticInsanity**
…and not rack size.

This fixes #1665.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java [hunk 1]
```diff
@@ -686,11 +687,21 @@ public boolean isCompatibleAmmo(AmmoType a1, AmmoType a2) {
...
+                            && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
+                };
+            } else {
+                predicate = part -> {
+                    return part instanceof AmmoStorage
+                            && thisType.equals(((AmmoStorage)part).getType())
+                            && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
+                };
+            }
+            AmmoStorage a = (AmmoStorage)campaign.findSparePart(predicate);
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:704]: This could be done through a ternary instead to cut down on near identical code (image is because I wasn't sure if it would work or not)
image

Comment (ChaoticInsanity) [reply MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:704]: In my personal opinion I think in this case the readability of the if statement is a greater benefit. The compiler is not going to care and there will be no performance loss. But if you really prefer the ternary I can put it in and test/commit it.

Comment (NickAragua) [reply MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:704]: If you go with the suggested option, you'll need to put in a comment explaining what to do - I personally find complicated ternary statements difficult to parse, and someone looking at that code a year from now will need it explained.

Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:704]:
```suggestion
            AmmoStorage a = (AmmoStorage) campaign.findSparePart(predicate);
```

File: MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java [hunk 2]
```diff
@@ -686,11 +687,21 @@ public boolean isCompatibleAmmo(AmmoType a1, AmmoType a2) {
...
+                predicate = part -> {
+                    return part instanceof AmmoStorage
+                            && thisType.equalsAmmoTypeOnly(((AmmoStorage)part).getType())
+                            && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
+                };
+            } else {
+                predicate = part -> {
+                    return part instanceof AmmoStorage
+                            && thisType.equals(((AmmoStorage)part).getType())
+                            && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:701]:
```suggestion
                            && thisType.equals(((AmmoStorage) part).getType())
                            && thisType.getMunitionType() == ((AmmoType) ((AmmoStorage) part).getType()).getMunitionType();
```

File: MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java [hunk 3]
```diff
@@ -686,11 +687,21 @@ public boolean isCompatibleAmmo(AmmoType a1, AmmoType a2) {
...
-                return part instanceof AmmoStorage
-                    && thisType.equals(((AmmoStorage)part).getType())
-                    && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
-            });
+            Predicate<Part> predicate;
+            if (AmmoBin.ALLOWED_BY_TYPE.contains(thisType.getAmmoType())) {
+                predicate = part -> {
+                    return part instanceof AmmoStorage
+                            && thisType.equalsAmmoTypeOnly(((AmmoStorage)part).getType())
+                            && thisType.getMunitionType() == ((AmmoType)((AmmoStorage)part).getType()).getMunitionType();
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java:695]:
```suggestion
                            && thisType.equalsAmmoTypeOnly(((AmmoStorage) part).getType())
                            && thisType.getMunitionType() == ((AmmoType) ((AmmoStorage) part).getType()).getMunitionType();
```

**Comment by ChaoticInsanity** [comment]
Are you sure you want those whitespace changes? That would cause this particular code to differ from the rest of the code base which does not have these extra whitespaces.

**Comment by Windchild292** [comment]
The rest of the codebase should have them, trying to get it fixed bit by bit.

**Comment by ChaoticInsanity** [comment]
Ok, makes sense.
