### PR TITLE
Issue 5256: Refactored MekHQ Unit's Gunners to be Set to ensure gunners are unique

### LINKED ISSUE #5256: Dead pilot automatically replaced by live pilot upon scenario resolution in MekHQ, and live pilot is already assigned to mech. Pilot now assigned to two mechs and unassigning doesn't stick.
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I lost a pilot to death by skin of teeth optional rule ejection after a fatal medium laser hit to the cockpit. Upon resolving the scenario, the mech assigned to the dead pilot now is assigned to another pilot of the same mech type/refit, in this case the Wolverine 'Breaker B'. I name them to help keep track of their service, and the dead pilot was from the one named 'C' and the now double-assigned pilot is from the one named 'B'.

I cannot remove the alive pilot from the mech that they are erroneously assigned to easily, I had to restart, remove the mech from TO&E, remove pilot from all units in personnel, and remove pilot from both mechs in hangar, and restarted again to ensure it stuck. Before resolving, even mothballing showed the weird erroneous assignment which shouldn't be possible, and they showed on the TO&E in both Support Company > Lead Lance and Support Company > Support Lance under my Lead Battalion entry.

### Steps to Reproduce

Lose pilot in megamek due to skin of teeth ejection from head damage while having a non deployed pilot in a matching mech, resolve scenario, new pilot showed up in both 'mechs and was hard to remove.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

_No response_

### Attach Files

[files.zip](https://github.com/user-attachments/files/17942178/files.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by psikomonkie**
…rs are unique

Fixes #5256

### CODE REVIEW

**Comment by IllianiCBT** [comment]
Looks like we have some failing tests

**Comment by psikomonkie** [comment]
Fixes #5256

File: MekHQ/unittests/mekhq/gui/model/UnitTableModelTest.java [hunk 1]
```diff
@@ -66,7 +66,12 @@ private void setCrew(int driverCount, int totalDriverNeeds,
                          boolean hasNavigator, Entity entity,
                          String expected) {
         List<Person> drivers = Collections.nCopies(driverCount, crewMember);
-        List<Person> gunners = Collections.nCopies(gunnerCount, crewMember);
+
+        Set<Person> gunners = new HashSet<>();
+        for(int i = 0; i < gunnerCount; i++){
```
Comment (IllianiCBT) [inline MekHQ/unittests/mekhq/gui/model/UnitTableModelTest.java:71]: Let's pop a whitespace after `for`

**Review by IllianiCBT — APPROVED** [review]
