### PR TITLE
1902: Fixing DateChooser NPEs

### LINKED ISSUE #1902: 47.8 - NPE changing campaign date
Encountered the following error when attempting to change campaign date in mekhq, campaign options -> general.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: temporal
	at java.util.Objects.requireNonNull(Unknown Source)
	at java.time.format.DateTimeFormatter.formatTo(Unknown Source)
	at java.time.format.DateTimeFormatter.format(Unknown Source)
	at mekhq.gui.dialog.DateChooser$1.valueToString(DateChooser.java:175)
	at javax.swing.JFormattedTextField$AbstractFormatter.install(Unknown Source)
	at javax.swing.JFormattedTextField.setFormatter(Unknown Source)
	at javax.swing.JFormattedTextField.setValue(Unknown Source)
	at javax.swing.JFormattedTextField.setFormatterFactory(Unknown Source)
	at mekhq.gui.dialog.DateChooser.<init>(DateChooser.java:165)
	at mekhq.gui.dialog.CampaignOptionsDialog.btnDateActionPerformed(CampaignOptionsDialog.java:5118)

Save file and customs:
[customs.zip](https://github.com/MegaMek/mekhq/files/5029602/customs.zip)

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #1902

### CODE REVIEW

File: MekHQ/src/mekhq/gui/dialog/DateChooser.java [hunk 1]
```diff
@@ -158,32 +157,27 @@ public DateChooser(JFrame owner, LocalDate d) {
...
-            dateField.addKeyListener(this);
-            dateField.setFormatterFactory(new DefaultFormatterFactory(new JFormattedTextField.AbstractFormatter() {
-                private static final long serialVersionUID = -5512863073174935806L;
-
-                @Override
-                public Object stringToValue(String text) {
-                    return MMDDYYYY.parse(text);
-                }
+        dateField = new JFormattedTextField(date);
+        dateField.setToolTipText("Date of the transaction.");
```
Comment (NickAragua) [inline MekHQ/src/mekhq/gui/dialog/DateChooser.java:161]: Might not be a transaction per se
