### PR TITLE
Issue #2418: Ensure context menu shortcut works on our tables

### LINKED ISSUE #2418: No Way to Reliably Trigger Right-click Context Menu from Keyboard
### Environment
What version of MekHQ does your issue apply to? 0.47.17
What operating system are you using?  WIndows
What java version are you using?  1.8.0_281

### Description
User Impact
It is impossible to reliably trigger the right click context menu from the keyboard. This makes certain tasks such as assigning personnel difficult to impossible with a screen reader.

Repro Steps:
1. Activate MekHQ.
2. Load a campaign with an existing roster for simplicity.
3. Move to the personnel tab.
4. Move into the personnel table with Tab and go down a few rows as appropriate.
5. Attempt to open the context menu from the keyboard. Press shift+F10 and the applications menu key.

Actual Results
Shift+f10 opens the Windows "System," menu, with "minimize," "restore," etc. The application key appears to do nothing on my system, though this may be specific to my setup. In any case both shortcuts should ideally be supported.

Expected Results
A way should be provided to open this menu from the keyboard reliably across all platforms.

Possible Resolutions:
Add a shortcut such that shift+f10 opens the context menu on the selected item in keyboard focus, much as right click does for the mouse.

### Files

NA

### PR DESCRIPTION
**Pull request by sixlettervariables**
This adds a new abstract class `JPopupMenuAdapter` to help connect the keyboard chord SHIFT+F10 to all of our context menus on JTable's and JTree's. This fixes #2418.

Apparently SHIFT+F10 sometimes works, but not always. This removes all doubt.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java [hunk 1]
```diff
@@ -72,38 +74,35 @@ public void actionPerformed(ActionEvent action) {
...
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        int row = financeTable.getSelectedRow();
+        if (row < 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:87]: I'm pretty sure this is not necessary with the check in shouldShowPopup.

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java [hunk 2]
```diff
@@ -72,38 +74,35 @@ public void actionPerformed(ActionEvent action) {
     }
 
     @Override
-    public void mousePressed(MouseEvent e) {
-        maybeShowPopup(e);
+    protected boolean shouldShowPopup() {
+        return financeTable.getSelectedRowCount() > 0;
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:78]:
```suggestion
        return (financeTable.getSelectedRowCount() > 0) && gui.getCampaign().isGM();
```

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:78]: The popup is only a GM menu, and thus shouldn't show up if they aren't a GM.

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+
+    @Override
+    public void mousePressed(MouseEvent e) {
+        maybeShowPopup(e);
+    }
+
+    @Override
+    public void mouseReleased(MouseEvent e) {
+        maybeShowPopup(e);
+    }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:82]: Could this cause it to show up twice?

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+
+            @Override
+            public void actionPerformed(ActionEvent e) {
+                // Immediately return if there are no units selected
+                if (!shouldShowPopup()) {
+                    return;
+                }
+
+                JPopupMenu popup = createPopupMenu();
+                popup.show(component, component.getX(), component.getY());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:64]: Missing null check

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java [hunk 5]
```diff
@@ -72,38 +74,35 @@ public void actionPerformed(ActionEvent action) {
...
     }
 
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        int row = financeTable.getSelectedRow();
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:84]: Why is the nullable like this instead of 
```
protected @Nullable JPopupMenu createPopupMenu()
```

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+    }
+
+    @Override
+    public void mouseReleased(MouseEvent e) {
+        maybeShowPopup(e);
+    }
+
+    private void maybeShowPopup(MouseEvent e) {
+        if (e.isPopupTrigger()) {
+            // Immediately return if there are no units selected
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:86]: The comment doesn't make sense anymore

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+    protected abstract boolean shouldShowPopup();
+
+    /**
+     * Creates the popup menu, or returns {@code null} if the
+     * popup menu should not be shown.
+     * @return A {@link JPopupMenu} to show, or {@code null} if no
+     *         popup menu should be shown.
+     */
+    @Nullable
+    protected abstract JPopupMenu createPopupMenu();
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:110]: Same nullable question

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java [hunk 8]
```diff
@@ -36,18 +34,22 @@
...
 
-    public FinanceTableMouseAdapter(CampaignGUI gui, JTable financeTable, FinanceTableModel financeModel) {
-        super();
+    protected FinanceTableMouseAdapter(CampaignGUI gui, JTable financeTable, FinanceTableModel financeModel) {
         this.gui = gui;
         this.financeTable = financeTable;
         this.financeModel = financeModel;
     }
 
+    public static void connect(CampaignGUI gui, JTable financeTable, FinanceTableModel financeModel) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:48]: Could this being static cause issues with your goal of testing these components?

File: MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java [hunk 9]
```diff
@@ -89,49 +89,46 @@ public void actionPerformed(ActionEvent action) {
...
 
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        if (loanTable.getSelectedRowCount() == 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java:101]: This check isn't necessary given the check in shouldShowPopup

File: MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java [hunk 10]
```diff
@@ -89,49 +89,46 @@ public void actionPerformed(ActionEvent action) {
...
-            menuItem.setEnabled(gui.getCampaign().isGM());
-            menu.add(menuItem);
-            // end
-            popup.addSeparator();
-            popup.add(menu);
-            popup.show(e.getComponent(), e.getX(), e.getY());
-        }
+
+        int row = loanTable.getSelectedRow();
+        Loan loan = loanModel.getLoan(loanTable.convertRowIndexToModel(row));
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java:106]: could inline this

File: MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java [hunk 11]
```diff
@@ -250,170 +242,178 @@ public boolean areAllPartsPodded(Part[] parts) {
...
+    protected boolean shouldShowPopup() {
+        return partsTable.getSelectedRowCount() > 0;
+    }
+
+    @Override
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        if (partsTable.getSelectedRowCount() == 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java:255]: Should be removable.

File: MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java [hunk 12]
```diff
@@ -137,20 +137,40 @@
...
+                    int size = splitPersonnel.getDividerSize();
+                    if ((width - location + size) < PersonnelTab.PERSONNEL_VIEW_WIDTH) {
+                        // expand
+                        splitPersonnel.resetToPreferredSizes();
+                    } else {
+                        // collapse
+                        splitPersonnel.setDividerLocation(1.0);
+                    }
+                }
+            }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java:170]: Why are we overriding this here when it is only ever used here? Why not have it as part of the base class?

File: MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java [hunk 13]
```diff
@@ -1,145 +1,131 @@
...
-                        for (int curRow : rows) {
-                            if (curRow < 0) {
-                                continue;
-                            }
-                            model.getAcquisition(table.convertRowIndexToModel(curRow))
-                                    .ifPresent(ProcurementTableMouseAdapter.this::procureAllItems);
-                        }
+            }
+        });
+        menuItem.setEnabled(gui.getCampaign().isGM());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java:77]: Noticed when reading through, this can be removed as the whole thing only shows if they are a GM

File: MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java [hunk 14]
```diff
@@ -1,145 +1,131 @@
...
-                            }
-                            model.getAcquisition(table.convertRowIndexToModel(curRow))
-                                    .ifPresent(a -> {
-                                        model.removeRow(row);
-                                        MekHQ.triggerEvent(new ProcurementEvent(a));
-                                    });
-                        }
+            }
+        });
+        menuItem.setEnabled(gui.getCampaign().isGM());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java:97]: Same here, can be removed

File: MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java [hunk 15]
```diff
@@ -1,145 +1,131 @@
...
-            menuItem.setEnabled(gui.getCampaign().isGM());
-            menu.add(menuItem);
-            // end
-            popup.addSeparator();
-            popup.add(menu);
-            popup.show(e.getComponent(), e.getX(), e.getY());
-        }
+            }
+        });
+        menuItem.setEnabled(gui.getCampaign().isGM());
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java:122]: Same here, can be removed

File: MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java [hunk 16]
```diff
@@ -1,145 +1,131 @@
...
     }
 
-    @SuppressWarnings("serial")
-    private void maybeShowPopup(MouseEvent e) {
+    @Override
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        // GM Only (for now)
+        if ((table.getSelectedRowCount() == 0) || !gui.getCampaign().isGM()) {
+            return null;
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java:45]: This can be removed

File: MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java [hunk 17]
```diff
@@ -35,61 +33,62 @@
...
 
-    private void maybeShowPopup(MouseEvent e) {
+    @Override
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        int row = scenarioTable.getSelectedRow();
+        if (row < 0) {
+            return null;
+        }
+
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java:66]: Can't this be removed?

File: MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java [hunk 18]
```diff
@@ -139,125 +140,121 @@ public void actionPerformed(ActionEvent action) {
...
 
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        if (servicedUnitTable.getSelectedRowCount() == 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java:152]: Can't this be removed?

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java [hunk 19]
```diff
@@ -146,13 +146,32 @@
...
+                    if ((width - location + size) < HangarTab.UNIT_VIEW_WIDTH) {
+                        // expand
+                        splitUnit.resetToPreferredSizes();
+                    } else {
+                        // collapse
+                        splitUnit.setDividerLocation(1.0);
+                    }
+                }
+            }
+        }.connect(unitTable);
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java:172]: Same as personnel, why are we not just overriding this is the class given it is only used there?

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java [hunk 20]
```diff
@@ -524,570 +543,565 @@ public void actionPerformed(ActionEvent action) {
...
 
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        if (unitTable.getSelectedRowCount() == 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java:555]: Same again, can be removed

File: MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java [hunk 21]
```diff
@@ -144,86 +146,88 @@ public void actionPerformed(ActionEvent action) {
...
-                return;
-            }
-            IPartWork partWork = taskModel.getTaskAt(taskTable.convertRowIndexToModel(row));
-            if (null == partWork) {
-                return;
-            }
+        int row = taskTable.getSelectedRow();
+        if (row < 0) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java:167]: Can be removed

File: MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java [hunk 22]
```diff
@@ -590,539 +593,608 @@ public void actionPerformed(ActionEvent action) {
...
 
     @Override
-    public void mouseReleased(MouseEvent e) {
-        maybeShowPopup(e);
-    }
+    @Nullable
+    protected JPopupMenu createPopupMenu() {
+        if (tree.getSelectionPaths() == null) {
+            return null;
+        }
```
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java:605]: This can be removed

File: MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java (hunk 9 above)
Comment (Windchild292) [inline MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java:101]: Can be removed.

**Review by Windchild292 — COMMENTED** [review]
Lots of comments, but largely they have to do with createPopupMenu having checks covered in shouldShowPopup, which is always called before it.

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java (hunk 1 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:87]: I don't like eschewing preconditions if they're not both private; but I think I can simplify this to a single method.

File: MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java (hunk 8 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java:48]: No, I don't really have a good way to test Swing components unfortunately.

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java (hunk 3 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:82]: Maybe? Doesn't appear to.

**Comment by sixlettervariables** [comment]
@Windchild292 I have changed the API of JPopupMenuAdapter to ensure it is used correctly from implementations. There no longer exists the possibility of a time lag between the pre-condition check and menu creation, ensuring implementations don't run into funny timing errors (e.g. menu takes a long time to create and in that space the user goes and right clicks something else).

I'll look into which mouse event to pop the context menu on.

File: MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java (hunk 3 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java:77]: This implementation is correct per:
https://docs.oracle.com/javase/tutorial/uiswing/components/menu.html#popup

**Comment by Windchild292** [comment]
Just two questions left, both about the mouse click override being overridden during the construction instead of just being overridden in the adapter itself. Otherwise, the changes here look good

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java (hunk 19 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java:173]: This is so I do not have to include the splitter as a variable in the class.

File: MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java (hunk 12 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java:169]: This is so I do not have to include the splitter as a variable in the class.

**Comment by sixlettervariables** [comment]
The splitter is a separate behavior I did not want tied to the base details, so it is kept only in the connect logic. I tried to separate it out but it didn't seem to work the same...and I honestly gave up on figuring out why.

**Review by Windchild292 — APPROVED** [review]
