### PR TITLE
Fixed Image Scaling Stopping Campaign Options IIC from Launching

### LINKED ISSUE #5975: Unable to open campaign options
### Brief Description *

Dev Branch, version 0.50.03
Started a fresh game with a fresh download. Only change made is the addition of custom icons and portraits and some tweaking of the portrait folders paths. In campaign screen, unable to open campaign options. Error message appears.

### 3. Steps to Reproduce

1. Launch game.
2. Load a save game.
3. Try to open campaign options.

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/18649165/mekhq.log)

[SOS.cpnx.gz](https://github.com/user-attachments/files/18649169/SOS.cpnx.gz)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

0.50.03

### Operating System *

Windows 10 10.0 (amd64)

### Java Version *

17.0.12

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Replaced manual image scaling logic with `scaleImageIconToWidth` utility function.
- Simplified and cleaned up code in `SelectPresetDialog`, `GeneralTab`, and `CampaignOptionsHeaderPanel` by leveraging the utility.

Fix #5975

### Dev Notes
Basically, this was caused by image-size hitting 0. At which point the scaling broke because you can't have a 0 dimension in an object. The naughty bit of code actually predated the image utility and never got updated (whoops).

### CODE REVIEW

File: MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java [hunk 1]
```diff
@@ -279,6 +273,7 @@ public AbstractMHQScrollablePanel createGeneralTab() {
      */
     private static JPanel createGeneralHeader() {
         ImageIcon imageIcon = new ImageIcon("data/images/misc/MekHQ.png");
+        imageIcon = scaleImageIconToWidth(imageIcon, UIUtil.scaleForGUI(200));
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java:276]: This wasn't necessary for the fix, I just wanted to shrink the image size and I might as well do it in this PR.
