### PR TITLE
Permanent injuries can't be replaced with temporal ones

### LINKED ISSUE #7565: [Issue] New non-permanent injuries can overwrite permanent injuries
### Brief Description *

Save 1: pilot Iuliu Biznosanu has a concussion that is a permanent injury, and has had so for approximately two years.

Save 2: After being deployed to a mission and injured, pilot has suffered a cerebral contusion, a higher tier of injury to the brain that puts him out of action for 90 days.

Save 3: Save just before the contusion is supposed to heal.

Save 4: the cerebral contusion's 90 days have passed and it healed. In doing so, it has overwritten the original permanent injury. He has sustained critical head trauma and healed it by taking even more severe head trauma. It should probably not work that way.

### 3. Steps to Reproduce

_No response_

### Attach Files

[The Alley Cats30410707.cpnx.gz](https://github.com/user-attachments/files/22503167/The.Alley.Cats30410707.cpnx.gz)

[The Alley Cats30410723.cpnx.gz](https://github.com/user-attachments/files/22503176/The.Alley.Cats30410723.cpnx.gz)

[The Alley Cats30411125.cpnx.gz](https://github.com/user-attachments/files/22503209/The.Alley.Cats30411125.cpnx.gz)

[The Alley Cats30411127.cpnx.gz](https://github.com/user-attachments/files/22503217/The.Alley.Cats30411127.cpnx.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

50.06

### Operating System *

Windows 11

### Java Version *

Java 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by VicenteCartas**
Fixes #7565 

The bug report explains the issue pretty well: the worsening of a permanent injury could replace it by a temporal one. This happens in multiple injuries types, not just concussions.

This fix takes the decision that permanent injuries are chronic damage, so combat stress cannot affect them. But non-permanent injuries (representing non chronic injuries) can be made worse by stress. By not returning any GameEffect, the permanent injuries will be left alone.

Added also a parametrized unit test to validate this based on PR feedback.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/personnel/medical/advancedMedical/InjuryTypes.java [hunk 1]
```diff
@@ -883,6 +908,11 @@ public String getSimpleName(int severity) {
 
         @Override
         public List<GameEffect> genStressEffect(Campaign campaign, Person person, Injury injury, int hits) {
+            // Permanent injuries have stabilized and should not worsen or be replaced by temporary ones
+            if (injury.isPermanent()) {
+                return Collections.emptyList();
+            }
```
[the remark this answers is not in the document]
Comment (VicenteCartas) [reply MekHQ/src/mekhq/campaign/personnel/medical/advancedMedical/InjuryTypes.java]: Added a parametrized test to make sure all permanent injuries behave correctly (do not generate temporal injuries).

File: MekHQ/src/mekhq/campaign/personnel/medical/advancedMedical/InjuryTypes.java
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/personnel/medical/advancedMedical/InjuryTypes.java]: Will this worsen if it's a permanent injury? This should be handled like how it is at lines 939-944, I think.

Comment (VicenteCartas) [reply MekHQ/src/mekhq/campaign/personnel/medical/advancedMedical/InjuryTypes.java]: Good point! Updated.
