### PR TITLE
Fix #6711: Fixed Conventional Infantry & Large Vessel (DropShip) Mothballing and Activation

### LINKED ISSUE #6711: [Issue]Conventional Infantry Gm activate/mothball only
### Brief Description *

Conventional infantry can only be activated or mothballed with GM mode. Per rules, the CI units do their own maintence, and should be able to mothball/activate themselves 

### 3. Steps to Reproduce

_No response_

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

0.50.04

### Operating System *

Windows 11

### Java Version *

161

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #6711 

### Dev Notes
This PR addresses some issues with activating and mothballing self-crewed units. Specifically conventional infantry and DropShips. These units will now correctly mothball and activate.

### CODE REVIEW

**Review by HammerGS — APPROVED** [review]
Checked with AI no issues found.

File: MekHQ/src/mekhq/gui/CampaignGUI.java [hunk 1]
```diff
@@ -1769,25 +1770,41 @@ public void refitUnit(Refit r, boolean selectModelName) {
...
+                }
+
+                if (unit.getEntity().isLargeCraft()) {
+                    Unit techUnit = tech.getUnit();
+                    // This stops vessel crew from other vessels appearing in the list
+                    if (techUnit != null && !techUnit.equals(unit)) {
+                        continue;
+                    }
+                }
+            }
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/gui/CampaignGUI.java:1798]: Why do we need to stop vessel crew from other vessels appearing in the list? Similar Q regarding `MothballUnitAction` where it restricts it to units on the vessels crew.

**Review by psikomonkie — APPROVED** [review]
Nice! I do have a question around why someone has to be on the crew of a large vessel to mothball it (see comment), but it's not something that blocks this.

File: MekHQ/src/mekhq/gui/CampaignGUI.java (hunk 1 above)
Comment (IllianiBird) [reply MekHQ/src/mekhq/gui/CampaignGUI.java:1798]: Because they're self-crewed units. So the mothball and activation needs to (ideally) be performed by the personnel on the crew. We employ a bit of handwavium for activating large vessels by allowing an unassigned vessel crew member to perform the activation in the event the vessel has no crew. We disallow personnel assigned to other vessels as personnel cannot be assigned to more than one unit.

Comment (psikomonkie) [reply MekHQ/src/mekhq/gui/CampaignGUI.java:1798]: Ooh, I see, that really wasn’t connecting in my head. Thanks Illiani!
