### PR TITLE
Hangar Tab Popup List: Bulk Selection and Rank Fixes

### LINKED ISSUE #1417: GM Tools, Hanger improvement
### Environment
NA
### Description
In the Hanger, in GM tools, the option to mothball/activate instantly has been put in.   It however only applies to *single* units, you cannot choose several units to demothball or mothball.  Would it be possible to fix this?

### Files
NA

### PR DESCRIPTION
**Pull request by Windchild292**
This is a bunch of changes to improve and modify the hangar tab popup list. I've modified most of the commands so that they work with a single unit or multiple, removes items from the list based on whether or not they are applicable, and added rank to the Hangar Mothball/Activate inputs.
Additionally, I added rank to the Warehouse and Repair bay tabs to make it easier to figure out the rank of our active techs.
As part of this, number 7 of #1542 will be implemented, and it fixes #1417.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/Campaign.java [hunk 1]
```diff
@@ -1887,14 +1898,22 @@ public Person findBestInRole(int role, String skill) {
...
             }
         }
 
         // Return the tech collection sorted worst to best
         // Reverse the sort if we've been asked for best to worst
         if (sorted) {
+            // First order by the amount of time the person has remaining, with the highest amount
+            // of time being at the top of the list
+            if (eliteFirst) {
+                techs.sort(Comparator.comparingInt(Person::getMinutesLeft));
```
Comment (NickAragua) [inline MekHQ/src/mekhq/campaign/Campaign.java]: How is this "elite first"?

File: MekHQ/src/mekhq/gui/utilities/StaticChecks.java [hunk 2]
```diff
@@ -4,7 +4,9 @@
 import java.util.UUID;
 import java.util.Vector;
 
+import megamek.common.BattleArmor;
```
Comment (NickAragua) [inline MekHQ/src/mekhq/gui/utilities/StaticChecks.java]: Why add these imports?

File: MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java [hunk 3]
```diff
@@ -106,14 +102,16 @@ public MassMothballDialog(Frame parent, Unit[] units, Campaign campaign, boolean
         gbc.weightx = 3;
         JLabel instructionLabel = new JLabel();
         instructionLabel.setBorder(new LineBorder(Color.BLUE));
-        instructionLabel.setText("<html>Choose the techs to carry out mothball/reactivation operations on the displayed units. <br/>A * indicates that the tech is currently maintaining units.</html>");
```
Comment (NickAragua) [inline MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java]: While you're in this file, there's a bug in this dialog that shows activation time cost to be the same as mothball time cost, where it should be 1/2 the time. Do you think you can track it down?

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/campaign/Campaign.java]: It works in practice, but I can't for the life of me understand why.

File: MekHQ/src/mekhq/gui/utilities/StaticChecks.java (hunk 2 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/utilities/StaticChecks.java]: Weird, the changes looked like they had been reverted when i first opened this PR. They were part of one stage of this branch, but I ended up reverting them

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/utilities/StaticChecks.java]: Reverted

File: MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java (hunk 3 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java]: I'll take a look, and I've actually got an idea of where it is.

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java]: Fixed, and found another bug that is somewhat related that I fixed at the same time.

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/Campaign.java]: This doesn't sort elites first. The code which does is on line 1934:
```
                // Return, swapping the value if we're looking to have Elites ordered first
                return eliteFirst ? -retVal : retVal;
```
I think the logic should be revised for this block, as it stands it doesn't make much sense (even if it produces the desired results).

File: MekHQ/src/mekhq/gui/RepairTab.java [hunk 4]
```diff
@@ -856,7 +857,7 @@ public void refreshTaskList() {
 
     public void refreshTechsList() {
         int selected = techTable.getSelectedRow();
-        ArrayList<Person> techs = getCampaign().getTechs(true, null, false, false);
+        List<Person> techs = getCampaign().getTechs(true, null, true, false);
```
Comment (sixlettervariables) [inline MekHQ/src/mekhq/gui/RepairTab.java]: A comment explaining the unnamed arguments would be nice. Hard to say what this does outside of an IDE (and even within you have to hover).

File: MekHQ/src/mekhq/gui/WarehouseTab.java [hunk 5]
```diff
@@ -670,8 +668,7 @@ protected void updateTechTarget() {
     }
 
     public void refreshTechsList() {
-        ArrayList<Person> techs = getCampaign().getTechs(true, null, false, false);
-        techsModel.setData(techs);
+        techsModel.setData(getCampaign().getTechs(true, null, true, false));
```
Comment (sixlettervariables) [inline MekHQ/src/mekhq/gui/WarehouseTab.java]: A comment here as well would be nice. Also, if `getTechs(true, null, true, false)` is the new default, how about a descriptively named method on Campaign?

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java [hunk 6]
```diff
@@ -244,60 +311,43 @@ public void actionPerformed(ActionEvent action) {
...
-                                            "A file already exists for this unit, cannot tag as custom. (Unit name and model)",
-                                            "File Already Exists",
-                                            JOptionPane.ERROR_MESSAGE);
-                            return;
-                        }
-                        FileOutputStream out = new FileOutputStream(
-                                fileNameCampaign);
-                        PrintStream p = new PrintStream(out);
+                String fileName = unit.getEntity().getChassis() + " " + unit.getEntity().getModel();
+                if (unit.getEntity() instanceof Mech) {
```
Comment (sixlettervariables) [inline MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java]: Could this be moved into a method? This massive if...elseif block is unruly as it stands.

File: MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java [hunk 7]
```diff
@@ -605,454 +629,508 @@ public void mouseReleased(MouseEvent e) {
...
+                    popup.add(menuItem);
+                }
+
+                // sell unit
+                if (gui.getCampaign().getCampaignOptions().canSellUnits()) {
+                    popup.addSeparator();
+                    menuItem = new JMenuItem("Sell Unit");
+                    menuItem.setActionCommand(COMMAND_SELL);
+                    menuItem.addActionListener(this);
+                    menuItem.setEnabled(!unit.isDeployed());
```
Comment (sixlettervariables) [inline MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java]: Should this be protected by `oneSelected`? It currently checks if the unit is deployed.

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java]: This should be hidden behind a check that ensures that one is not deployed, instead of enabling/disabling if the first unit is deployed. I've fixed that

File: MekHQ/src/mekhq/gui/RepairTab.java (hunk 4 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/RepairTab.java]: Ah, within Idea it shows all the variable names inline if you use values like true, null, "", or false.
I'll add a comment.

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/RepairTab.java]: image

File: MekHQ/src/mekhq/gui/WarehouseTab.java (hunk 5 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/WarehouseTab.java]: It isn't the default, just used in these two places. Added the comment though

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/campaign/Campaign.java]: I've added comments which should make it easier to understand.

Comment (sixlettervariables) [reply MekHQ/src/mekhq/campaign/Campaign.java]: I guess I don't follow. If you *don't* want elites first, why wouldn't you still want the person with the most time left?

Comment (Windchild292) [reply MekHQ/src/mekhq/campaign/Campaign.java]: Yes, this is used for Mothballing, which you always want a person with the most time left sorted to the top while the best personnel are the worst skilled. Annoying logic, but it works and looks good in practice.
