### PR TITLE
Corrected Briefing Room Combat Team Counter

### LINKED ISSUE #6434: [Issue][0.50.04] failed contract requirements
### Brief Description *

I received a "Advance Day" warning that i will not meet the contract requirements
But the display in the Breefing Room does show that i failded to provide  the required forces

Image

Advancing the day will result in a loss of CVP 

Image

I suspect that the Forces with "Auxiliary" Roll do count to the Total shown in the Display Room
bit not for the concract. I have added a screenshot of the contract in case it is relevant
Image

### 3. Steps to Reproduce

Step 1: load save game
Step 2: Advance a Day

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MegaMek Suite Version *

0.50.04

### Operating System *

Windows 10

### Java Version *

Eclipse Temurin JRE 17.0.14

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have included all necessary information and files to help reproduce this issue
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiCBT**
- Introduced `isCombatRole` method in `CombatRole` enum to classify roles as combat-related (FRONTLINE, MANEUVER, PATROL).
- Updated deployment eligibility logic in `LanceAssignmentView` to account for Cadre Duty contracts and suitable role classification (`isTraining` or `isCombatRole`).

Fix #6434

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java [hunk 1]
```diff
@@ -125,19 +143,18 @@ public static CombatRole parseFromString(final String text) {
             case "IN_RESERVE", "UNASSIGNED" -> RESERVE;
             default -> {
                 MMLogger.create(CombatRole.class)
-                    .warn(String.format("Unable to parse %s into an CombatRole. Returning RESERVE.",
-                        text));
+                      .warn(String.format("Unable to parse %s into an CombatRole. Returning RESERVE.", text));
```
Comment (rjhancock) [inline MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java:146]: `.warn(String.format("Unable to parse %s into an CombatRole. Returning RESERVE.", text))`

can be `.warn("Unable to parse {} into an CombatRole. Returning RESERVE.", text)` and save some characters and overhead.

I know this is just the formatter kicking in, but just letting you know.

**Review by rjhancock — APPROVED** [review]
