### PR TITLE
Adjusted Prisoner Event Chances; Updated Prisoner Documentation

### LINKED ISSUE #6396: [Issue] Posted at Illanis request for prisoners
### Brief Description *

Apparently events poping up to often

### 3. Steps to Reproduce

_No response_

### Attach Files

[Lyran Dragoons27520303.cpnx.gz](https://github.com/user-attachments/files/19437140/Lyran.Dragoons27520303.cpnx.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.04

### Operating System *

Windows 10

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.13

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
- Modified overflow calculation to use percentage instead of a fixed value for better scaling.
- Updated event roll logic to reflect percentage-based overflow calculations.
- Reduced event roll range from 0-100 to 0-50 for minor and major event determination.
- Refactored `checkForPrisonerEvents` to accept parameters for better control and reduced reliance on campaign context.
- Updated test cases in `PrisonerEventManagerTest` to align with refactored method and improve coverage.
- Updated related documentation: updated "Prisoners of War & Abstracted Search and Rescue" and removed outdated PDF from the StratCon directory.

Fix #6396

### Dev Notes
I've moved the documentation into a new 'Random Events' folder, as prisoner events can now occur in non-AtB campaigns.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java [hunk 1]
```diff
@@ -155,17 +153,20 @@ public PrisonerEventManager(Campaign campaign) {
 
         // Fortnightly events
         if (isMonday && isFortnight) {
-            checkForPrisonerEvents(false);
+            int totalPrisoners = campaign.getCurrentPrisoners().size();
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java:156]: Functionality change

File: MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java [hunk 2]
```diff
@@ -222,48 +223,71 @@ List<Boolean> checkForRansomEvents() {
...
+     *       <ul>
+     *         <li>The first element is {@code true} if a minor event occurred, {@code false} otherwise.</li>
+     *         <li>The second element is {@code true} if a major event occurred, {@code false} otherwise.</li>
+     *       </ul>
      */
-    List<Boolean> checkForPrisonerEvents(boolean isHeadless) {
-        int totalPrisoners = campaign.getCurrentPrisoners().size();
-        int prisonerCapacityUsage = calculatePrisonerCapacityUsage(campaign);
-        int prisonerCapacity = calculatePrisonerCapacity(campaign);
+    List<Boolean> checkForPrisonerEvents(boolean isHeadless, int totalPrisoners, int prisonerCapacityUsage, int prisonerCapacity) {
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java:258]: A bunch of functionality changes

File: MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/PrisonerEventManagerTest.java [hunk 3]
```diff
@@ -27,39 +27,36 @@
  */
```
Comment (IllianiCBT) [inline MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/PrisonerEventManagerTest.java:27]: A bunch of functionality changes in this class

**Review by Sleet01 — APPROVED** [review]
LGTM
