### PR TITLE
Fix #7856: Fixed New Day Error; Renamed Methods to Reduce Room for Confusion

### LINKED ISSUE #7856: [Issue] Uncaught Exception on New Day [NI 10-27]
### Brief Description *

Advanced to a New Day with a convoy interception battle and got a pop up for an uncaught exception. Presently unknown what caused it.  Can still launch the battle. Nothing seems to have outright broken.

Image

this is the error block that I could find. But the entire log is in the folder.

[Issue Package.zip](https://github.com/user-attachments/files/23175823/Issue.Package.zip)

### 3. Steps to Reproduce

_No response_

### Attach Files

_No response_

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

50.10 NI 10-27

### Operating System *

Windows 11

### Java Version *

Adoptium 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
This was caused by us incorrectly accessing a List as if it were a Map.

We have two very similarly named methods, to reduce room for confusion, moving forward I went ahead and renamed them.

Marking as 'high' as the trigger conditions are very common.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/CampaignNewDayManager.java [hunk 1]
```diff
@@ -1708,7 +1708,7 @@ private void processNewDayATBScenarios() {
             for (final AtBScenario atBScenario : contract.getCurrentAtBScenarios()) {
                 if ((atBScenario.getDate() != null) && atBScenario.getDate().equals(today)) {
                     int forceId = atBScenario.getCombatTeamId();
-                    if ((campaign.getAllCombatTeams().get(forceId) != null) &&
+                    if ((campaign.getCombatTeamsAsMap().get(forceId) != null) &&
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/CampaignNewDayManager.java:1711]: This is the only functionality change. The rest is renaming the two methods.
