### PR TITLE
Fix #6048, #7836: Fixed Parts in Use & Warehouse & Shopping List All Using Invalid Data When Campaign Includes Biped & Quadruped (and Possibly Tripod) 'Meks of the Same Weight

### LINKED ISSUE #6048: [Issue] Mek Rear Legs requestion incorrectly
### Brief Description *

Noticed an odd thing where the requested stock function was very determinedly ordering one Mek Rear Right Leg and one Mek Rear Left Leg every week for my Scorpion. After several months of ordering them every week, I have 1 Mek Rear Left Leg, 2 Mek Rear Right Leg, 68 Mek Left legs, and 65 Mek Right Legs. 

Which is to say that every time a rear leg is ordered, a regular leg shows up and the system goes "Boy, I'd better order another one!" in an infinite loop.

### 3. Steps to Reproduce

_No response_

### Attach Files

[The Alley Cats30320213.cpnx.gz](https://github.com/user-attachments/files/18839097/The.Alley.Cats30320213.cpnx.gz)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

50.03

### Operating System *

Windows 11

### Java Version *

Java 17

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #7836: [Issue] Administrators keep ordering RL for 55 ton units
### Brief Description *

At least once a month my administrators decide I need a right leg for a 55-ton mech.  I have a Scorpion and a Coronus.  I currently have 9 Rear Right Legs.

### 3. Steps to Reproduce

Advance the game for several weeks and a RL will show up

### Attach Files

[logs.zip](https://github.com/user-attachments/files/23144098/logs.zip)

[42nd Raging Buffalos30690118.cpnx.gz](https://github.com/user-attachments/files/23144102/42nd.Raging.Buffalos30690118.cpnx.gz)

[mechfiles.zip](https://github.com/user-attachments/files/23144103/mechfiles.zip)

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely.

### MekHQ Suite Version *

50.10-nightly-2025-10-17

### Operating System *

Windows 11

### Java Version *

17.0.12

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #6048
Fix #7836

Basically, we had a bunch of faulty logic in our 'is same part' methods for MekLocation and our 'equals' checker in Parts in Use that were incorrectly equivocating biped limbs and quadruped (and probably tripod) with their biped equivalent. This resulting in Parts in Use checking the warehouse, seeing the player was out of one type of leg, putting in a new order, but that new order was of the other type of leg. This led to a situation where new legs would be ordered on a weekly basis.

While I was at it I also cleaned up some of the conditionals so that the logic is easier to follow. This should help reduce the risk of a similar issue occurring again in the future.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/PartInUse.java [hunk 1]
```diff
@@ -232,15 +232,29 @@ public int hashCode() {
...
-                     Objects.equals(getTechBase(), other.getTechBase());
+
+        // First, try to match using String comparison. This is weak, so we need extra checks
+        final PartInUse otherPartInUse = (PartInUse) object;
+        boolean haveMatchingDescriptions = this.description.equals(otherPartInUse.description);
+
+        // Next, check they're the same item
+        Part targetPart = getPartToBuy().getAcquisitionPart();
+        Part otherTargetPart = otherPartInUse.getPartToBuy().getAcquisitionPart();
+        boolean isSamePart = targetPart.isSamePartType(otherTargetPart);
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/parts/PartInUse.java:251]: Will this impact BA suits or other parts that have the same description but are still considered the same part? (BA Suits description includes the squad size iirc)

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/PartInUse.java:251]: Potentially, lemme double-check and if it does I can see if I can work in a fix.

If it _does_ impact them then that impact is pre-existing. The string comparison isn't something I added.

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/PartInUse.java:251]: As discussed on Discord confirmed to be a visual bug only
