### PR TITLE
Fix AtBMonthlyContractMarket payment multiplier

### LINKED ISSUE #4952: [0.50.01-SNAPSHOT] AtB contract market generates contracts with very high base pay values.
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When generating contracts through the AtB Contract Marker, contracts generate with very high base pay values. This is more visible on more mature mercenary companies where the expected values are clearly inflated on the higher end. When comparing payouts of contracts generated in previous versions compared to contracts generated on current, we notice up to ten times increase in payout value. 

The base pay range seems quite broad, suggesting a faulty multiplier somewhere. 
It is hard to reliably detect in new companies, though batch creating contracts will result in some contracts generating with a much higher base pay that is expected (up to 20 - 40 million range). 

The workaround is to manually lower the base pay values (suggested divide by 10). 

### Steps to Reproduce

Generate new contracts with GM mode using the AtB contract markets, and monitor the expected profits and base pay values. 
If possible, compare newly generated contracts from a previous version with one from a current version. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1 - Rev. b5a4f6a63622f97b768c9dcb2124f544cc986ce8

### Attach Files

[1st Rimward Hussars_NEW.zip](https://github.com/user-attachments/files/17195491/1st.Rimward.Hussars_NEW.zip)
[customs.zip](https://github.com/user-attachments/files/17195495/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by Algebro7**
There was an error when calculating the payment multiplier using the CamOps unit rating method for AtBMonthly contracts, which was caused by incorrectly using the reputation score instead of the reputation modifier for determining this multiplier. This PR does a couple of things:

1. Fixes `getReputationFactor()` to use the camopsUnitRatingMod instead of the reputation score
2. Reverts the change in `AtBMonthlyContractMarket` and uses the `AtBUnitRatingMod` instead
3. Adds a `getCamOpsUnitRatingMod()` method to get the camops unit rating mod and support `getReputationFactor()`
4. Adds docstrings for everything

Closes #4952

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/Campaign.java [hunk 1]
```diff
@@ -6851,11 +6850,26 @@ public int getAtBUnitRatingMod() {
                 : reputation.getAtbModifier();
     }
 
+    /**
+     * Retrieves the unit rating modifier as described in Campaign Operations. This value is equal
+     * to the total reputation score divided by ten, rounded down to the nearest whole number.
+     *
+     * @return The unit rating modifier as described in Campaign Operations.
+     */
+    public int getCamOpsUnitRatingMod() {
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/campaign/Campaign.java:6859]: Is there value in moving this into the Reputation class - cooking dinner so the class might be called something else? Call the new method something like `getReputationModifier()`.

**Review by IllianiCBT — CHANGES_REQUESTED** [review]

File: MekHQ/src/mekhq/campaign/Campaign.java (hunk 1 above)
Comment (Algebro7) [reply MekHQ/src/mekhq/campaign/Campaign.java:6859]: I did actually try to do that first, but there is already a different getReputationModifier() there that does something based on the unit experience levels instead. I wasn't sure how that was used and so I didn't want to mess with it--could you look at that when you get a minute and let me know what you think?

Thanks!

Comment (IllianiCBT) [reply MekHQ/src/mekhq/campaign/Campaign.java:6859]: I’ll take a look once I’ve had dinner.
