### PR TITLE
Fix: Prevent infinite MRMS loop when AmmoBin repair can't be fulfilled (#7414)

### LINKED ISSUE #7414: [Issue] Running auto-repair on a damaged mech taken out of being mothballed leads to thousands of autorepair/salvage actions
### Brief Description *

Very strange mass repair/salvage bug.

Image

I actived a mothballed Highlander. It has damage, and custom ammo loadouts in the bins.

This has generated thousands of actions for auto-repair/salvage and is borderline crashing my MHQ.

### 3. Steps to Reproduce

1. Unmothballed a damaged Highlander with a weird ammo load-out
2. Autorepair/salvage works each day
3. Thousands of repair/salvage actions iterated through

### Attach Files

[unified_log.log](https://github.com/user-attachments/files/21437668/unified_log.log)

[Talon Security Services30630726-massiveautorepairbug.cpnx.gz](https://github.com/user-attachments/files/21437671/Talon.Security.Services30630726-massiveautorepairbug.cpnx.gz)

[Customs.zip](https://github.com/user-attachments/files/21437673/Customs.zip)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

MekHQ-0.50.07-nightly-2025-07-23

### Operating System *

Win11

### Java Version *

Java 17 Adoptium

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by VicenteCartas**
## Summary

Fixes #7414 — MRMS generates thousands of futile repair actions when auto-repairing a mech with AmmoBins that need reloading but no matching ammo exists in the warehouse.

## Root Cause

The Highlander HGN-733 in the bug report has Precision AC/10 AmmoBins that need reloading (`shotsNeeded > 0`), but the warehouse has no Precision AC/10 ammo. MRMS's `filterParts()` did not check ammo availability before including AmmoBins in the repair list — unlike `Armor`, which already had a supply check via `checkArmorSupply()` / `Armor.isInSupply()`.

Without this check, AmmoBin parts entered the repair pipeline, `loadBin()` loaded 0 rounds (nothing available), `repairPart()` reported success, and the outer while-loop in `performUnitMRMS()` retried indefinitely — consuming all tech time and generating thousands of futile actions.

PR #8519 (Issue #8496, merged in v0.50.11) changed how carryover time is calculated in `repairPart()`, which incidentally altered the code path enough that the loop no longer triggers. But the root cause — AmmoBins without available ammo entering the repair list — was never addressed.

### Primary: Filter AmmoBins without available ammo (MRMSService + AmmoBin)

Added `AmmoBin.isAmmoAvailable()`, mirroring `Armor.isInSupply()`. Then added `checkAmmoSupply()` in `MRMSService.filterParts()`, following the same pattern as the existing `checkArmorSupply()`. AmmoBins are now excluded from the repair list when the warehouse has no ammo of the needed type.

### Secondary: Quartermaster hardening

- `removeAmmo(AmmoStorage, int)` now removes 0-shot AmmoStorage entries from the warehouse when encountered, instead of silently returning 0
- `addAmmo()` guards tightened from `shots >= 0` to `shots > 0` to prevent creating empty entries (both regular and infantry overloads)

### Legacy save cleanup (CampaignXmlParser)

The warehouse rebuild during campaign load now skips spare AmmoStorage entries with 0 shots, cleaning up any pre-existing empty entries from older saves.

## Related Issues / PRs

- #7414 — The original bug report (this PR)
- #8496 / PR #8519 — MRMS carryover fix that incidentally masked the loop
- #7912 — Related ammo bin issues
- #6633 / MegaMek PR #6883 — ACAR desync ammo types
- MekHQ PR #7935 — Destroyed ammo bins unable to map to equipment

### CODE REVIEW

File: MekHQ/unittests/mekhq/service/mrms/MRMSServiceTest.java [hunk 1]
```diff
@@ -898,4 +899,99 @@ private void arrangeTestMRMSUnitsCarryover(SkillLevel skillLevel, int techMinute
...
+
+            // Find the AmmoBin on the unit and make it need reloading
+            List<AmmoBin> ammoBins = unit.getParts().stream()
+                  .filter(p -> p instanceof AmmoBin)
+                  .map(p -> (AmmoBin) p)
+                  .toList();
+
+            // The UrbanMech UM-R69 should have at least one AmmoBin (for its Ultra AC/10)
+            assert !ammoBins.isEmpty() : "UrbanMech should have ammo bins";
+
```
[the remark this answers is not in the document]
Comment (VicenteCartas) [reply MekHQ/unittests/mekhq/service/mrms/MRMSServiceTest.java:945]: Learned something new :O

File: MekHQ/unittests/mekhq/service/mrms/MRMSServiceTest.java
Comment (psikomonkie) [inline MekHQ/unittests/mekhq/service/mrms/MRMSServiceTest.java]: Should be `2025-2026`

File: MekHQ/src/mekhq/campaign/Quartermaster.java
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/Quartermaster.java]: Should be like `2020-2026`.
