### PR TITLE
Fix #8386: Fixed Loading & Parsing of 'Any Tech' Acquisitions Method

### LINKED ISSUE #8386: [Issue] Error Message keeps popping up, blocking the program.
### Brief Description *

I load up my old save file from 0.50.06 and it keeps giving me this error popup. 
Uncaught Exception java.lang.NullPointerException

### 3. Steps to Reproduce

1. Load the game.
2.Pick one of the presets.
3. You should see the error message.

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/23813723/mekhq.log)

[Helsinki Metalworks30640725.cpnx.gz](https://github.com/user-attachments/files/23813767/Helsinki.Metalworks30640725.cpnx.gz)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

0.50.10

### Operating System *

Windows 10

### Java Version *

 Java Vendor: Eclipse Adoptium Java Version: 21.0.7

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #8386

One of the options for acquisitions resolution is 'any tech'. We were trying to parse that option as if it were a skill called 'Any Tech'. Obviously, that didn't work and how this passed testing I will never know - because I specifically tested the CamOps stock preset which _uses_ this option

Regardless, this PR fixes the initial issue while also changing how we handle this option to use an enum instead of hardcoded Strings. This will prevent this issue reoccurring. Compatibility handler is included.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptionsUnmarshaller.java [hunk 1]
```diff
@@ -156,7 +156,17 @@ private static boolean parseNodeName(Version version, String nodeName, CampaignO
...
-            case "acquisitionSkill" -> campaignOptions.setAcquisitionSkill(nodeContents);
+            case "acquisitionSkill" -> {
+                AcquisitionsType newType = switch (nodeContents) {
+                    case "Administration" -> AcquisitionsType.ADMINISTRATION;
+                    case "Negotiation" -> AcquisitionsType.NEGOTIATION;
+                    case "Automatic Success" -> AcquisitionsType.AUTOMATIC;
+                    default -> AcquisitionsType.ANY_TECH;
+                };
+                campaignOptions.setAcquisitionType(newType);
+            }
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptionsUnmarshaller.java:167]: Compatibility handler
