### PR TITLE
Fix #7063, #7726, #7777: Added Crew Validation for Units On Load & On Refit

### LINKED ISSUE #7063: [50.06] Vehicles/Dropships remain overstaffed after Customize reduces overall staffing req causing Reputation hit
### Brief Description *

After Customizing a vehicle or dropship to require less crew, the extra crew remain, overstaffing the vehicle. (Example: Buffel Engineering Support Vehicle customized to remove all weapons was staffed at 5/2, and had 3 Gunners still on the crew. Excalibur Dropship was customized to have less weapons, ended up 18/16 with too many gunners still on staff.) 

This resulted in -5 Support Rating for Partially Crewed Large Craft Modifier in reputation for being overstaffed.

### 3. Steps to Reproduce

1. Spawn in a multi crewed anything.
2. Customize it to reduce overall crew count (remove/reduce weapons for example so gunners are no longer/less needed).
3. Finalize the customization with GM Mode.
4. Go to Hangar > View: Status. Crew count is now overstaffed.
5. Advance to next monday. Observe reputation hit for Partially Crewed Large Craft Modifier (if changing dropship?)

### Attach Files

[Autosave-1-Valkyrie Legion-30420508.cpnx.gz](https://github.com/user-attachments/files/20325755/Autosave-1-Valkyrie.Legion-30420508.cpnx.gz)

[mekfiles.zip](https://github.com/user-attachments/files/20325768/mekfiles.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.06

### Operating System *

Windows 11

### Java Version *

17.0.12.7

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #7726: [Issue][05.07] Dropship crew requirements incorrect after update, Dropships nonfunctional.
### Brief Description *

Dropships Crew Requirement increased when updating from 06 to 07, from 16 to 27 crew needed. Unable to actually add any crew beyond 16 to meet new listed demand.

### 3. Steps to Reproduce

Update from .06 to .07.
Check Hangar, all Dropships are highlighted purple with incorrect crewing.
Attempt to add crew. Cannot.

### Attach Files

[Valkyrie Legion Custom Builds.zip](https://github.com/user-attachments/files/22896628/Valkyrie.Legion.Custom.Builds.zip)

THIS IS THE .07 SAVE
[Valkyrie Legion30451026.cpnx.gz](https://github.com/user-attachments/files/22896631/Valkyrie.Legion30451026.cpnx.gz)

THIS IS THE .06 SAVE
[Valkyrie Legion30451026.cpnx.gz](https://github.com/user-attachments/files/22896677/Valkyrie.Legion30451026.cpnx.gz)

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### MekHQ Suite Version *

0.50.07

### Operating System *

Windows 11

### Java Version *

17.0.12.7

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### LINKED ISSUE #7777: [Issue] 0.50.10-nightly-2025-10-19 Issue with convoy forces
### Brief Description *

MekHQ is not detecting the planetlifters assigned as convoy forces, does not seem to work even if the parent unit is assigned as a convoy force or not. Savefile should be on May 1st 3039, one day before the convoy prompt box appears for ease of testing.

### 3. Steps to Reproduce

1. Advance Day
2. 0 Tons for Unit Supply Capacity

### Attach Files

[MekHQ Bug Report Stuff.zip](https://github.com/user-attachments/files/23001464/MekHQ.Bug.Report.Stuff.zip)

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

0.50.10-nightly-2025-10-19

### Operating System *

Windows 11

### Java Version *

Java 17.0.16_8

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #7063
Fix #7726
Fix #7777

This PR adds a small check when loading a campaign unit that confirms the unit's current crew is not overstaffed. This can occur if how we calculate crew sizes ever changes - such as happened recently with aerial support vehicles. It can also happen following a refit.

Speaking of refits, this check will also run following a refit to ensure that crew sizes are still correct.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/Refit.java [hunk 1]
```diff
@@ -1495,14 +1495,6 @@ private void complete() {
...
         oldUnit.setRefit(null);
         Entity oldEntity = oldUnit.getEntity();
-        List<Person> soldiers = new ArrayList<>();
-        // unload any soldiers to reload later, because troop size may have changed
-        if (oldEntity instanceof Infantry) {
-            soldiers = oldUnit.getCrew();
-            for (Person soldier : soldiers) {
-                oldUnit.remove(soldier, true);
-            }
-        }
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/parts/Refit.java:1505]: This is no longer needed, see next comment for context

File: MekHQ/src/mekhq/campaign/parts/Refit.java [hunk 2]
```diff
@@ -1711,12 +1703,10 @@ private void complete() {
         oldUnit.initializeAllTransportSpace();
         campaign.updateTransportInTransports(oldUnit);
 
-        // reload any soldiers
-        for (Person soldier : soldiers) {
-            if (!oldUnit.canTakeMoreGunners()) {
-                break;
-            }
-            oldUnit.addPilotOrSoldier(soldier);
```
Comment (IllianiBird) [inline MekHQ/src/mekhq/campaign/parts/Refit.java:1719]: This is handled better by the new method added by this PR

**Review by psikomonkie — APPROVED** [review]
Nice!

File: MekHQ/src/mekhq/campaign/unit/Unit.java [hunk 3]
```diff
@@ -6997,4 +7002,62 @@ public static PartQuality getRandomUnitQuality(int modifier) {
...
+        int targetGunnerCount = usesSoloPilot() ? targetDriverCount : getTotalGunnerNeeds();
+        while (!gunners.isEmpty() && (gunners.size() > targetGunnerCount)) {
+            Iterator<Person> gunnersIterator = gunners.iterator();
+            if (gunnersIterator.hasNext()) {
+                Person removedPerson = gunnersIterator.next();
+                remove(removedPerson, true);
+                String report = getFormattedTextAt(RESOURCE_BUNDLE, "Unit.excessCrew.gunner", warningString,
+                      CLOSING_SPAN_TAG, getHyperlinkedName(), removedPerson.getHyperlinkedName());
+                reports.add(report);
+                reports.add(getHyperlinkedName() + ": " + targetGunnerCount);
```
[the remark this answers is not in the document]
Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/unit/Unit.java]: Fixed
