### PR TITLE
1723: Fixing Missing Personnel and Hangar Tab Selection Highlights

### LINKED ISSUE #1723: 0.47.6 Nimbus theme missing selection highlights
As of 0.47.6 release selection highlights in "Personnel" and "Hangar" tabs do not display properly. The highlight appears to use white instead of usual dark blue. Highlighting in remaining tabs works properly. See provided screencap for details.

Missing selection highlight

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #1723. The first four commits are code cleanup and refactoring, the fifth adds the force icon for the graphical hangar display, and the sixth is the bugfix.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/model/UnitTableModel.java [hunk 1]
```diff
@@ -352,19 +305,16 @@ public Component getTableCellRendererComponent(JTable table, Object value, boole
                 } else if (u.getActiveCrew().size() < u.getFullCrewSize()) {
                     applyColors(colors.getUncrewed());
                 } else {
-                    setBackground(UIManager.getColor("Table.background"));
                     setForeground(UIManager.getColor("Table.foreground"));
+                    setBackground(UIManager.getColor("Table.background"));
```
Comment (sixlettervariables) [inline MekHQ/src/mekhq/gui/model/UnitTableModel.java:309]: Why does this order matter and others do not seem to?

**Review by sixlettervariables — APPROVED** [review]
One question.

File: MekHQ/src/mekhq/gui/model/UnitTableModel.java (hunk 1 above)
Comment (Windchild292) [reply MekHQ/src/mekhq/gui/model/UnitTableModel.java:309]: It doesn't, I removed it as part of my testing and put it back in a different order... and didn't consider it worth a commit to swap back.
