### PR TITLE
Issue 6084: Clear leadership units when setting a new scenario.

### LINKED ISSUE #6084: [Issue] VTOLs pulled into air scenario when adding an air lance
### Brief Description *

Image

The VTOLs also cannot be undeployed from the scenario in the TOE, so they are stuck in it.

### 3. Steps to Reproduce

No clue.  I added an air lance and the 2 VTOLs were also pulled into the mission.

### Attach Files

Files are attached here:
https://github.com/MegaMek/mekhq/issues/6079

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### MekHQ Suite Version *

50.03

### Operating System *

Windows 11

### Java Version *

17.0.11

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by psikomonkie**
When deploying units for a new scenario it was not clearing the previously selected units. In some circumstances, like if a frontline unit is deployed in one mission and a bonus BA is deployed, and the next mission doesn't have a front line unit, then said bonus BA will get deployed again on its own. 

This PR fixes that by clearing the selected units from when setting the wizard a new scenario. 

Fixes #6084

### CODE REVIEW

File: MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java [hunk 1]
```diff
@@ -101,12 +100,6 @@ public StratconScenarioWizard(Campaign campaign, StratconPanel parent) {
         this.campaign = campaign;
         this.parent = parent;
         this.setModalityType(ModalityType.APPLICATION_MODAL);
-
-        for (CampaignTransportType campaignTransportType : getLeadershipDropdownVectorPair().stream().map(Pair::getValue).collect(Collectors.toSet())) {
```
Comment (IllianiCBT) [inline MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java:105]: Why is this no longer needed?

Comment (psikomonkie) [reply MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java:105]: Never did anything! It was from a removed attempt at adding the transport menu to this wizard. I can revert this if it should be on its own.

Comment (IllianiCBT) [reply MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java:105]: The transport stuff is your code, so I trust you to know whether it's needed or not so no need to revert. I was just curious :D

**Review by IllianiCBT — APPROVED** [review]
Fingers crossed we can put this to bed.
