### PR TITLE
Fix #7771: Fixed Ordering from Parts in Use & autoLogistics when Two Identical Items of Differing Tech Bases Exist in Use

### LINKED ISSUE #7771: [Issue] 50.07 Parts in Use only Combines clan and IS weapons with the same name, and only orders 1 variant.
### Brief Description *

If a weapon has a clan and IS variant such as an ER Large Laser, the parts in use report and auto-logistics will only see one of the variants.  I have included an example picture with an IS and Clan mech purchased.  Each mech has 2 ER Large Lasers of that tech base, and the logistics system is set to buy 100% of what is in use.

Expected result 2 Clan ER Large Laser and 2 IS ER Large Laser.
Actual result 4 IS ER Large Laser.

This also makes the buy buttons in the Parts in Use report much less useful if the players force is mixed tech, because it only can buy one type, and the type it is buying is not clear.

### 3. Steps to Reproduce

1.  Create an IS mech with ER large laser in a force.
2. Set auto-logistics to replace some percentage of the weapon.
3. Create a Clan mech with a Clan ER large laser in the force.  
4. Advance enough days that auto logistics have ordered all replacement weapons.
5. Check the warehouse, the autologistics will likely have ordered only weapons of one tech base, as if all the weapons were in one category.

### Attach Files

Image

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### MekHQ Suite Version *

50.07

### Operating System *

Windows 10

### Java Version *

17.0.14.7

### Final Verification

- [x] I confirm this is a single, unique issue that hasn't been reported before
- [x] I have filled and provided all necessary information above
- [x] I have included any and all logs, custom units, and CPNX (save) files
- [x] I have asked on MegaMek Discord about this issue
- [x] I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ

### PR DESCRIPTION
**Pull request by IllianiBird**
Fix #7771

The way Parts in Use works is it uses string comparison to match parts. Unfortunately, those strings didn't include tech base. So two items with identical names but different techs bases (ER Medium Laser [IS] vs. ER Medium Laser [Clan], for example) would be seen as the same item. This was also reflected in the stored parts in use 'memory'.

This PR adds tracking of Tech Base, including a new Tech Base column. Due to the way autoLogistics data is stored this has required wiping of old memory.

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/parts/PartInUse.java [hunk 1]
```diff
@@ -117,6 +120,10 @@ public String getDescription() {
         return description;
     }
 
+    public TechBase getTechBase() {
+        return techBase;
```
Comment (psikomonkie) [inline MekHQ/src/mekhq/campaign/parts/PartInUse.java]: You can get tech base from the `partToBuy`, no need to have the information saved separately.

```partToBuy.getTechBase();```

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/PartInUse.java]: I think you have the right of it here, and I don't know why I didn't do that. Cheers! :)

Comment (IllianiBird) [reply MekHQ/src/mekhq/campaign/parts/PartInUse.java]: Done

Comment (psikomonkie) [reply MekHQ/src/mekhq/campaign/parts/PartInUse.java]: Perfect timing! I was just checking Github one last time before bed.

**Review by psikomonkie — APPROVED** [review]
Nice!
