### PR TITLE
3038: Fixing missing Personnel Table Integer Comparators 

### LINKED ISSUE #3038: [49.6] Sorting of personnel by XP (all) and Age (only dependents) isn't correct
### Environment
MekHQ 49.6
Windows 10
Adoptium (Temurin 11)

### Description
The sorting of personnel by experience points and the sorting of dependents by age is not correct since 49.6.

### Files
Example Dependent
Example XP

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #3038 and a few other missing comparators I noticed while investigating.

### CODE REVIEW

File: MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java [hunk 1]
```diff
@@ -877,10 +877,14 @@ public boolean isVisible(final Campaign campaign, final PersonnelTabView view,
             case ORIGIN_PLANET:
             case PORTRAIT_PATH:
                 return new NaturalOrderComparator();
-            case SALARY:
-                return new FormattedNumberSorter();
-            case SKILL_LEVEL:
```
Comment (NickAragua) [inline MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java:882]: What happened to SKILL_LEVEL?

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java:882]: Nothing happened, no accidental removal at all...

**Review by NickAragua — APPROVED** [review]
