### PR TITLE
Issue #2358: Add missing lances on CPNX load

### LINKED ISSUE #2358: Forces not available in deployment screen
### Environment
What version of MekHQ does your issue apply to? 0.47.16
What operating system are you using?  Windows
What java version are you using?  ver 8

### Description
Most of my forces are not showing in the deployment list. I have a full clan cluster of units broken down by stars, but only four of them appear to be deployable. 

### Files
[Nightstalkers30610921 - Arrive at Hamburg.cpnx.zip](https://github.com/MegaMek/mekhq/files/5792127/Nightstalkers30610921.-.Arrive.at.Hamburg.cpnx.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5792128/customs.zip)
[logs.zip](https://github.com/MegaMek/mekhq/files/5792129/logs.zip)

### PR DESCRIPTION
**Pull request by sixlettervariables**
I'm not sure of the root cause, but it appears that sometimes we do not correctly update the AtB lance list in Campaign. On load we now verify that the AtB lance list contains _at least_ the lances that should be there.

Fixes #2358.

Loading the Campaign in question:
```
17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Command Star to AtB list

17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Scout Star to AtB list

17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Striker Star to AtB list

17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Hover Point I to AtB list

17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Hover Point II to AtB list

17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Hover Point III to AtB list

17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Hover Point IV to AtB list

17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Hover Point V to AtB list

17:42:55,460 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Track Star to AtB list

17:42:55,463 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Wheel Star to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance PHawk IIC Point to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Stinger IIC Point to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Wasp IIC Point to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance PHawk Point to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Osprey Point to AtB list

17:42:55,464 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Sabutai Point to AtB list

17:42:55,465 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Stuka Point to AtB list

17:42:55,465 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Gotha Point to AtB list

17:42:55,465 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Tyre Point to AtB list

17:42:55,465 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Issus Point to AtB list

17:42:55,467 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance DropShip Star II to AtB list

17:42:55,474 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance DropShip Star I to AtB list

17:42:55,475 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance HQ Point to AtB list

17:42:55,475 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Coolant Point to AtB list

17:42:55,475 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance MASH Point to AtB list

17:42:55,475 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Long Tom Point to AtB list

17:42:55,476 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Recovery Point to AtB list
```

### CODE REVIEW

File: MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java [hunk 1]
```diff
@@ -359,6 +360,17 @@ else if (xn.equalsIgnoreCase("info")) {
             }
         }
 
+        // determine if we've missed any lances and add those back into the campaign
+        if (retVal.getCampaignOptions().getUseAtB()) {
+            Hashtable<Integer, Lance> lances = retVal.getLances();
+            for (Force f : retVal.getAllForces()) {
+                if (f.getUnits().size() > 0 && (null == lances.get(f.getId()))) {
```
Comment (Windchild292) [inline MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java:367]:
```suggestion
                if ((f.getUnits().size() > 0) && (null == lances.get(f.getId()))) {
```

**Review by Windchild292 — APPROVED** [review]
