### PR TITLE
2091: Fixing missing requirement of addToCampaign

### LINKED ISSUE #2091: Unable to Add Unit in Add Loot/Potential Rewards dialog of editing scenario
WINDOWS 10, 47.10

I checked it in new campaign, and behavior is the same. No matter what type of unit I choose, nothing shows up on Summary tab, no matter what unit I check. Add button doesn't work, and whole interface is unresponsive. It takes some fancy moving to be able to click Cancel finally.

Moreover, it seems to be some global error in MekHQ database, because the same behavior happens in MegaMek battle, when started from MekHQ campaign. Nothing shows up, when you try to Add Unit to force from list. Clear MegaMek instance seems to work fine in that case.

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #2091

### CODE REVIEW

File: MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java [hunk 1]
```diff
@@ -143,10 +143,12 @@ public Entity getSelectedEntity() {
         Entity entity = super.getSelectedEntity();
         if (entity == null) {
             selectedUnit = null;
-            buttonSelect.setEnabled(false);
-            buttonSelect.setText(Messages.getString("MechSelectorDialog.Buy", TARGET_UNKNOWN));
-            buttonSelect.setToolTipText(null);
-        } else {
+            if (addToCampaign) {
```
Comment (NickAragua) [inline MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java:146]: What about the other case?

Comment (Windchild292) [reply MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java:146]: No changes required.

**Review by NickAragua — APPROVED** [review]
